import '../models/yoga_pose.dart';
import '../models/yoga_session.dart';

class YogaLibrary {
  static const List<YogaPose> posesCatalog = [
    YogaPose(
      id: 'pose_mountain',
      name: 'Mountain Pose (Tadasana)',
      category: 'Posture & Alignment',
      difficulty: 'Beginner',
      durationSeconds: 45,
      setup: 'Stand tall with feet hip-width apart, arms relaxed at sides.',
      steps: ['Ground all four corners of feet into the floor.', 'Engage quadriceps and lift chest.', 'Roll shoulders back and down.'],
      breathing: 'Deep diaphragmatic nasal breathing.',
      benefits: 'Improves posture, grounding, and axial spinal length.',
      modifications: 'Feet wider apart for improved balance.',
      safetyNotes: 'Keep knees soft, avoid locking joints.',
    ),
    YogaPose(
      id: 'pose_child',
      name: 'Child\'s Pose (Balasana)',
      category: 'Restorative',
      difficulty: 'Beginner',
      durationSeconds: 60,
      setup: 'Kneel on mat, big toes touching, knees wide.',
      steps: ['Sit hips back toward heels.', 'Extend arms forward on mat.', 'Rest forehead gently on floor.'],
      breathing: 'Slow exhale into low back and ribs.',
      benefits: 'Gently stretches lower back, hips, and shoulders.',
      modifications: 'Place cushion under forehead or knees.',
      safetyNotes: 'Avoid if experiencing acute knee pain.',
    ),
    YogaPose(
      id: 'pose_cat_cow',
      name: 'Cat-Cow Flow (Marjaryasana-Bitilasana)',
      category: 'Spinal Mobility',
      difficulty: 'Beginner',
      durationSeconds: 60,
      setup: 'Tabletop position on hands and knees.',
      steps: ['Inhale: Arch spine, drop belly, lift chest (Cow).', 'Exhale: Round spine, tuck chin to chest (Cat).'],
      breathing: 'Coordinate movement directly with breathing cadence.',
      benefits: 'Enhances thoracic and lumbar spinal fluid mobility.',
      modifications: 'Perform seated if wrists are sensitive.',
      safetyNotes: 'Move within pain-free Range of Motion.',
    ),
    YogaPose(
      id: 'pose_downdog',
      name: 'Downward-Facing Dog (Adho Mukha Svanasana)',
      category: 'Inversion & Stretch',
      difficulty: 'Beginner',
      durationSeconds: 60,
      setup: 'Start in tabletop, tuck toes under.',
      steps: ['Lift hips up and back toward ceiling.', 'Press firmly through palms.', 'Pedal heels gently toward floor.'],
      breathing: 'Steady rhythmic breathing.',
      benefits: 'Stretches hamstrings, calves, and lengthens spine.',
      modifications: 'Bend knees generously to relieve hamstrings.',
      safetyNotes: 'Keep wrists aligned under shoulder axis.',
    ),
    YogaPose(
      id: 'pose_cobra',
      name: 'Cobra Pose (Bhujangasana)',
      category: 'Back Extension',
      difficulty: 'Beginner',
      durationSeconds: 45,
      setup: 'Lie face down, palms under shoulders.',
      steps: ['Press tops of feet into floor.', 'Inhale and gently lift chest off ground.', 'Keep elbows close to ribcage.'],
      breathing: 'Inhale on extension lift.',
      benefits: 'Strengthens spine and opens anterior chest posture.',
      modifications: 'Baby Cobra: lower chest lift.',
      safetyNotes: 'Avoid compressing lumbar vertebrae.',
    ),
    YogaPose(
      id: 'pose_warrior_1',
      name: 'Warrior I (Virabhadrasana I)',
      category: 'Strength & Openness',
      difficulty: 'Beginner',
      durationSeconds: 45,
      setup: 'Step one foot forward 3-4 feet, back foot angled 45 degrees.',
      steps: ['Bend front knee to 90 degrees over ankle.', 'Raise arms overhead, shoulders relaxed.'],
      breathing: 'Full deep nasal breaths.',
      benefits: 'Strengthens legs, stretches hip flexors.',
      modifications: 'Shorter stance for balance.',
      safetyNotes: 'Ensure front knee stays tracking in line with toes.',
    ),
    YogaPose(
      id: 'pose_warrior_2',
      name: 'Warrior II (Virabhadrasana II)',
      category: 'Hip Opener',
      difficulty: 'Beginner',
      durationSeconds: 45,
      setup: 'Wide stance, front foot facing forward, back foot parallel to mat edge.',
      steps: ['Extend arms parallel to floor.', 'Gaze over front fingertips.', 'Sink hips low over bent knee.'],
      breathing: 'Calm, steady breathing.',
      benefits: 'Opens hips, groin, and chest muscles.',
      modifications: 'Straighten front leg slightly if tired.',
      safetyNotes: 'Keep torso upright above hips.',
    ),
    YogaPose(
      id: 'pose_tree',
      name: 'Tree Pose (Vrksasana)',
      category: 'Balance',
      difficulty: 'Beginner',
      durationSeconds: 45,
      setup: 'Stand tall on right foot.',
      steps: ['Place left foot sole against inner right thigh or calf.', 'Bring hands to heart center or overhead.'],
      breathing: 'Steady gaze and breathing.',
      benefits: 'Develops leg strength and proprioceptive balance.',
      modifications: 'Place foot on ankle as kickstand.',
      safetyNotes: 'Never place foot directly on side of knee joint.',
    ),
    YogaPose(
      id: 'pose_bridge',
      name: 'Bridge Pose (Setu Bandhasana)',
      category: 'Glute Activation',
      difficulty: 'Beginner',
      durationSeconds: 45,
      setup: 'Lie on back, knees bent, feet flat hip-width apart.',
      steps: ['Press heels into ground.', 'Lift hips toward ceiling.', 'Interlace fingers beneath back if comfortable.'],
      breathing: 'Inhale deeply as hips press up.',
      benefits: 'Strengthens glutes, posterior chain, and hip extension.',
      modifications: 'Place block under sacrum for support.',
      safetyNotes: 'Keep neck still and gaze straight up.',
    ),
    YogaPose(
      id: 'pose_seated_fold',
      name: 'Seated Forward Fold (Paschimottanasana)',
      category: 'Flexibility',
      difficulty: 'Beginner',
      durationSeconds: 60,
      setup: 'Sit with legs extended straight forward.',
      steps: ['Inhale and lengthen spine.', 'Exhale and hinge forward from hips toward feet.'],
      breathing: 'Exhale deeper into fold.',
      benefits: 'Stretches entire posterior hamstring and lumbar line.',
      modifications: 'Use strap around feet or bend knees.',
      safetyNotes: 'Maintain flat spine rather than rounding upper back.',
    ),
    YogaPose(
      id: 'pose_butterfly',
      name: 'Butterfly Pose (Baddha Konasana)',
      category: 'Hip & Groin',
      difficulty: 'Beginner',
      durationSeconds: 60,
      setup: 'Seated with soles of feet pressed together, knees wide.',
      steps: ['Hold feet or ankles.', 'Lengthen spine and gently let knees sink toward floor.'],
      breathing: 'Relaxed belly breathing.',
      benefits: 'Relieves inner thigh and groin tension.',
      modifications: 'Place blocks beneath knees.',
      safetyNotes: 'Never force knees down with arms.',
    ),
    YogaPose(
      id: 'pose_corpse',
      name: 'Corpse Pose (Savasana)',
      category: 'Restorative',
      difficulty: 'Beginner',
      durationSeconds: 120,
      setup: 'Lie flat on back, arms relaxed at sides, palms facing up.',
      steps: ['Close eyes.', 'Release all muscular tension.', 'Focus entirely on quiet breath.'],
      breathing: 'Effortless, natural respiration.',
      benefits: 'Down-regulates sympathetic nervous system and enhances recovery.',
      modifications: 'Place bolster beneath knees.',
      safetyNotes: 'Keep warm with light blanket.',
    ),
  ];

  static YogaSession generateRecoverySession({int durationMin = 10}) {
    return YogaSession(
      id: 'session_recovery_${DateTime.now().millisecondsSinceEpoch}',
      title: '10-Min Recovery & Mobility Flow',
      category: 'Recovery Yoga',
      durationMinutes: durationMin,
      poses: [
        posesCatalog[1], // Child's Pose
        posesCatalog[2], // Cat-Cow
        posesCatalog[3], // Downward Dog
        posesCatalog[4], // Cobra
        posesCatalog[8], // Bridge Pose
        posesCatalog[10], // Butterfly
        posesCatalog[11], // Corpse Pose
      ],
      guidanceNotes: 'Targeted restorative session designed to relieve fatigue and restore joint mobility.',
    );
  }
}
