import '../models/breathing_exercise.dart';

class BreathingLibrary {
  static const List<BreathingExercise> catalog = [
    BreathingExercise(
      id: 'breath_calm',
      name: 'Calm Breathing (4-4 Flow)',
      category: 'Morning Reset',
      difficulty: 'Beginner',
      durationSeconds: 120,
      cycles: 10,
      inhaleSeconds: 4,
      holdAfterInhaleSeconds: 0,
      exhaleSeconds: 4,
      holdAfterExhaleSeconds: 0,
      instructions: 'Inhale smoothly through your nose for 4 seconds, then exhale gently through your mouth for 4 seconds.',
      benefitsDescription: 'Down-regulates nervous system tension and balances heart rate variability.',
      safetyNotes: 'Keep your breath smooth and relaxed. Never strain.',
      recommendedContext: 'Morning Reset & Daily Stress Reduction',
    ),
    BreathingExercise(
      id: 'breath_box',
      name: 'Box Breathing (4-4-4-4)',
      category: 'Focus',
      difficulty: 'Beginner',
      durationSeconds: 160,
      cycles: 10,
      inhaleSeconds: 4,
      holdAfterInhaleSeconds: 4,
      exhaleSeconds: 4,
      holdAfterExhaleSeconds: 4,
      instructions: 'Inhale 4s, gently pause 4s, exhale 4s, gently pause 4s. Repeat equal sides.',
      benefitsDescription: 'Enhances cognitive focus, mental clarity, and situational composure.',
      safetyNotes: 'Holds should be relaxed and comfortable.',
      recommendedContext: 'Pre-Workout Mental Clarity & Deep Focus',
    ),
    BreathingExercise(
      id: 'breath_extended_exhale',
      name: 'Extended Exhale (4-6 Recovery)',
      category: 'Stress Reset',
      difficulty: 'Beginner',
      durationSeconds: 120,
      cycles: 12,
      inhaleSeconds: 4,
      holdAfterInhaleSeconds: 0,
      exhaleSeconds: 6,
      holdAfterExhaleSeconds: 0,
      instructions: 'Inhale through nose for 4 seconds. Exhale slowly for 6 seconds.',
      benefitsDescription: 'Activates parasympathetic nervous system response for deep physical calm.',
      safetyNotes: 'Exhale softly without forcing air out.',
      recommendedContext: 'Post-Workout Cool Down & Stress Reduction',
    ),
    BreathingExercise(
      id: 'breath_equal',
      name: 'Equal Breathing (Sama Vritti 5-5)',
      category: 'Calm',
      difficulty: 'Beginner',
      durationSeconds: 120,
      cycles: 12,
      inhaleSeconds: 5,
      holdAfterInhaleSeconds: 0,
      exhaleSeconds: 5,
      holdAfterExhaleSeconds: 0,
      instructions: 'Breathe in for 5 seconds and breathe out for 5 seconds in smooth cadence.',
      benefitsDescription: 'Equalizes oxygen flow and creates balanced mental stability.',
      safetyNotes: 'Maintain an upright, relaxed posture.',
      recommendedContext: 'General Relaxation & Daily Balance',
    ),
    BreathingExercise(
      id: 'breath_coherent',
      name: 'Coherent Breathing (5.5s Pace)',
      category: 'Recovery',
      difficulty: 'Beginner',
      durationSeconds: 132,
      cycles: 12,
      inhaleSeconds: 5,
      holdAfterInhaleSeconds: 0,
      exhaleSeconds: 5,
      holdAfterExhaleSeconds: 0,
      instructions: 'Inhale gently for 5 seconds and exhale for 5 seconds to achieve resonance.',
      benefitsDescription: 'Maximizes heart rate variability (HRV) resonance score.',
      safetyNotes: 'Keep shoulders relaxed and un-slouched.',
      recommendedContext: 'Active Recovery Days & Sleep Prep',
    ),
    BreathingExercise(
      id: 'breath_pre_workout',
      name: 'Pre-Workout Activation (3-2 Pulse)',
      category: 'Pre-Workout',
      difficulty: 'Beginner',
      durationSeconds: 90,
      cycles: 15,
      inhaleSeconds: 3,
      holdAfterInhaleSeconds: 0,
      exhaleSeconds: 2,
      holdAfterExhaleSeconds: 0,
      instructions: 'Breathe in briskly for 3 seconds, exhale forcefully for 2 seconds.',
      benefitsDescription: 'Prepares diaphragm and respiratory muscles for physical movement.',
      safetyNotes: 'Discontinue if feeling dizzy or lightheaded.',
      recommendedContext: 'Immediate Pre-Workout Warmup',
    ),
    BreathingExercise(
      id: 'breath_post_workout',
      name: 'Post-Workout Recovery (4-2-6-0)',
      category: 'Post-Workout',
      difficulty: 'Beginner',
      durationSeconds: 120,
      cycles: 10,
      inhaleSeconds: 4,
      holdAfterInhaleSeconds: 2,
      exhaleSeconds: 6,
      holdAfterExhaleSeconds: 0,
      instructions: 'Inhale 4s, slight pause 2s, slow exhale 6s to lower heart rate.',
      benefitsDescription: 'Expedites heart rate recovery post-workout.',
      safetyNotes: 'Sit or lie down in comfortable posture.',
      recommendedContext: 'Immediate Post-Workout Cooldown',
    ),
    BreathingExercise(
      id: 'breath_evening_wind_down',
      name: 'Evening Wind-Down (4-2-7-0)',
      category: 'Sleep Wind-Down',
      difficulty: 'Beginner',
      durationSeconds: 150,
      cycles: 10,
      inhaleSeconds: 4,
      holdAfterInhaleSeconds: 2,
      exhaleSeconds: 7,
      holdAfterExhaleSeconds: 0,
      instructions: 'Inhale 4s, pause 2s, long slow exhale 7s.',
      benefitsDescription: 'Promotes melatonin release and prepares body for restful sleep.',
      safetyNotes: 'Best performed lying in bed or seated comfortably.',
      recommendedContext: 'Nighttime Sleep Preparation',
    ),
    BreathingExercise(
      id: 'breath_body_scan',
      name: 'Body Scan Relaxation (4-2-4-2)',
      category: 'Beginner',
      difficulty: 'Beginner',
      durationSeconds: 120,
      cycles: 10,
      inhaleSeconds: 4,
      holdAfterInhaleSeconds: 2,
      exhaleSeconds: 4,
      holdAfterExhaleSeconds: 2,
      instructions: 'Inhale 4s, pause 2s, exhale 4s, pause 2s while relaxing facial muscles.',
      benefitsDescription: 'Releases subconscious muscular tension across neck and shoulders.',
      safetyNotes: 'Keep jaw unclenched and teeth apart.',
      recommendedContext: 'Post-Yoga & Stretching',
    ),
    BreathingExercise(
      id: 'breath_guided_relaxation',
      name: 'Guided Deep Relaxation (4-8 Flow)',
      category: 'Recovery',
      difficulty: 'Beginner',
      durationSeconds: 120,
      cycles: 10,
      inhaleSeconds: 4,
      holdAfterInhaleSeconds: 0,
      exhaleSeconds: 8,
      holdAfterExhaleSeconds: 0,
      instructions: 'Inhale 4s, long continuous exhale for 8s.',
      benefitsDescription: 'Deep parasympathetic calm and mental resetting.',
      safetyNotes: 'Keep breathing comfortable.',
      recommendedContext: 'Rest Days & Recovery Sessions',
    ),
  ];

  static BreathingExercise getDefaultSession({String category = 'Calm'}) {
    try {
      return catalog.firstWhere((b) => b.category.toLowerCase().contains(category.toLowerCase()));
    } catch (_) {
      return catalog.first;
    }
  }
}
