import 'package:flutter/material.dart';

/// Centralized localization class for FitnessElite.ai.
/// Supports 9 target languages:
/// Global: English (en), Spanish (es), Mandarin Chinese (zh), Hindi (hi), Arabic (ar - RTL)
/// India: Bengali (bn), Telugu (te), Marathi (mr), Tamil (ta)
class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ??
        AppLocalizations(const Locale('en'));
  }

  static const List<Locale> supportedLocales = [
    Locale('en'), // English
    Locale('es'), // Spanish
    Locale('zh'), // Mandarin Chinese
    Locale('hi'), // Hindi
    Locale('ar'), // Arabic (RTL)
    Locale('bn'), // Bengali
    Locale('te'), // Telugu
    Locale('mr'), // Marathi
    Locale('ta'), // Tamil
  ];

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'appName': 'FitnessElite.ai',
      'welcomeTitle': 'Elite AI Fitness',
      'welcomeSubtitle': 'Fitness Digital Twin! Your body. Simulated. Optimised.',
      'taglineCaps': 'YOUR BODY. SIMULATED. OPTIMIZED.',
      'fitnessInYourLanguage': 'Fitness, in your language.',
      'choosePreferredLanguage': 'Choose your preferred language. You can change this anytime.',
      'searchLanguage': 'Search language...',
      'getStarted': 'Get Started',
      'skip': 'Skip',
      'next': 'Next',
      'continueButton': 'Continue',
      'onboardingHeadline1': 'Understand your body.',
      'onboardingSubtitle1': 'FitnessElite.ai learns about your goals, lifestyle and fitness needs.',
      'onboardingHeadline2': 'Your plan. Powered by AI.',
      'onboardingSubtitle2': 'Get personalized workouts, nutrition guidance and progress insights built around you.',
      'onboardingHeadline3': 'Become your stronger self.',
      'onboardingSubtitle3': 'Track your progress and build habits that last.',
      'journeyStartsHere': 'Your journey starts here.',
      'authTitle': 'Authentication Foundation',
      'authSubtitle': 'Secure access to your biometric performance hub',
      'revisitOnboarding': 'Revisit Onboarding',
      'changeLanguage': 'Change Language',
      'welcomeToFitnessElite': 'Welcome to FitnessElite.ai',
      'authSubtitleTagline': 'Your personalized fitness journey starts here.',
      'signIn': 'Sign In',
      'createAccount': 'Create Account',
      'fullName': 'Full Name',
      'fullNameHint': 'Enter your full name',
      'emailAddress': 'Email Address',
      'emailHint': 'name@example.com',
      'password': 'Password',
      'confirmPassword': 'Confirm Password',
      'forgotPassword': 'Forgot Password?',
      'orDivider': 'OR',
      'continueWithGoogle': 'Continue with Google',
      'alreadyHaveAccount': 'Already have an account? Sign In',
      'dontHaveAccount': "Don't have an account? Create Account",
      'validationNameRequired': 'Full name is required',
      'validationEmailInvalid': 'Please enter a valid email address',
      'validationPasswordMin': 'Password must be at least 8 characters',
      'validationPasswordMatch': 'Passwords do not match',
      'errInvalidCredentials': 'Invalid email or password. Please try again.',
      'errNetwork': 'Network error. Check your connection and try again.',
      'errAccountCreation': 'Failed to create account. An account with this email may already exist.',
      'passwordResetSent': 'Password reset instructions sent to your email.',
      'healthProfileTitle': "Let's get to know you.",
      'signOut': 'Sign Out',
      'switchTheme': 'Switch Theme',
      'systemTheme': 'System',
      'lightTheme': 'Light',
      'darkTheme': 'Dark',
      'aiCoach': 'AI Coach',
      'workouts': 'Workouts',
      'nutrition': 'Nutrition',
      'progress': 'Progress',
      'healthAssessment': 'Health Assessment',
      'visionAssessment': 'Vision Assessment',

      // Step Titles
      'step1Title': 'Basic Information',
      'step1Subtitle': 'Tell us about yourself to calculate your biometric baseline.',
      'metricUnits': 'Metric (cm / kg)',
      'imperialUnits': 'Imperial (ft / lbs)',
      'age': 'Age',
      'sex': 'Sex',
      'male': 'Male',
      'female': 'Female',
      'otherSex': 'Non-binary / Other',
      'heightCm': 'Height (cm)',
      'weightKg': 'Weight (kg)',
      'heightFt': 'Feet',
      'heightIn': 'Inches',
      'weightLbs': 'Weight (lbs)',

      'step2Title': 'How active are you?',
      'step2Subtitle': 'Select the level that best describes your routine.',
      'sedentary': 'Sedentary',
      'sedentaryDesc': 'Little to no exercise, desk job',
      'lightlyActive': 'Lightly Active',
      'lightlyActiveDesc': 'Light exercise 1-3 days/week',
      'moderatelyActive': 'Moderately Active',
      'moderatelyActiveDesc': 'Moderate exercise 3-5 days/week',
      'veryActive': 'Very Active',
      'veryActiveDesc': 'Hard exercise 6-7 days/week',
      'extremelyActive': 'Extremely Active',
      'extremelyActiveDesc': 'Very hard exercise & physical job',

      'step3Title': 'What is your main fitness goal?',
      'step3Subtitle': 'Select your primary target.',
      'loseWeight': 'Lose weight',
      'buildMuscle': 'Build muscle',
      'improveFitness': 'Improve fitness',
      'improveEndurance': 'Improve endurance',
      'maintainWeight': 'Maintain weight',
      'improveHealth': 'Improve overall health',

      'step4Title': 'Lifestyle & Preferences',
      'step4Subtitle': 'Help us customize a plan around your schedule.',
      'workoutTimePerDay': 'Workout Time Per Day',
      'workoutDaysPerWeek': 'Preferred Days Per Week',
      'equipmentAvailable': 'Equipment Available',
      'sleepDuration': 'Sleep Duration',
      'dietaryPreference': 'Dietary Preference',

      'step5Title': 'Biometric Summary & BMI',
      'step5Subtitle': 'Locally calculated health baseline.',
      'bmiValue': 'BMI Index',
      'bmiDisclaimerTitle': 'Screening Metric Disclaimer',
      'bmiDisclaimerText': 'Body Mass Index (BMI) is a general screening metric based on height and weight. It does not measure body fat directly and is not a medical diagnosis.',
      'underweight': 'Underweight',
      'normalWeight': 'Normal weight',
      'overweight': 'Overweight',
      'obesity': 'Obesity',
      'finishAssessment': 'Complete Profile',
      'homeDashboardTitle': 'Welcome to FitnessElite',
      'homeDashboardSubtitle': 'Your fitness profile is active.',
    },
    'es': {
      'appName': 'FitnessElite.ai',
      'welcomeTitle': 'Fitness Elite IA',
      'welcomeSubtitle': 'Gemelo Digital de Fitness! Tu cuerpo. Simulado. Optimizado.',
      'taglineCaps': 'TU CUERPO. SIMULADO. OPTIMIZADO.',
      'fitnessInYourLanguage': 'Fitness, en tu idioma.',
      'choosePreferredLanguage': 'Elige tu idioma preferido. Puedes cambiarlo en cualquier momento.',
      'searchLanguage': 'Buscar idioma...',
      'getStarted': 'Comenzar',
      'skip': 'Omitir',
      'next': 'Siguiente',
      'continueButton': 'Continuar',
      'onboardingHeadline1': 'Entiende tu cuerpo.',
      'onboardingSubtitle1': 'FitnessElite.ai aprende sobre tus objetivos, estilo de vida y necesidades de fitness.',
      'onboardingHeadline2': 'Tu plan. Impulsado por IA.',
      'onboardingSubtitle2': 'Obtén entrenamientos personalizados, guía de nutrición e información sobre tu progreso.',
      'onboardingHeadline3': 'Conviértete en tu versión más fuerte.',
      'onboardingSubtitle3': 'Haz un seguimiento de tu progreso y crea hábitos duraderos.',
      'journeyStartsHere': 'Tu viaje comienza aquí.',
      'authTitle': 'Base de Autenticación',
      'authSubtitle': 'Acceso seguro a tu centro de rendimiento biométrico',
      'revisitOnboarding': 'Revisar Onboarding',
      'changeLanguage': 'Cambiar Idioma',
      'welcomeToFitnessElite': 'Bienvenido a FitnessElite.ai',
      'authSubtitleTagline': 'Tu viaje de fitness personalizado comienza aquí.',
      'signIn': 'Iniciar Sesión',
      'createAccount': 'Crear Cuenta',
      'fullName': 'Nombre Completo',
      'fullNameHint': 'Ingresa tu nombre completo',
      'emailAddress': 'Correo Electrónico',
      'emailHint': 'nombre@ejemplo.com',
      'password': 'Contraseña',
      'confirmPassword': 'Confirmar Contraseña',
      'forgotPassword': '¿Olvidaste tu contraseña?',
      'orDivider': 'O',
      'continueWithGoogle': 'Continuar con Google',
      'alreadyHaveAccount': '¿Ya tienes una cuenta? Iniciar Sesión',
      'dontHaveAccount': '¿No tienes una cuenta? Crear Cuenta',
      'validationNameRequired': 'El nombre completo es requerido',
      'validationEmailInvalid': 'Por favor ingresa un correo válido',
      'validationPasswordMin': 'La contraseña debe tener al menos 8 caracteres',
      'validationPasswordMatch': 'Las contraseñas no coinciden',
      'errInvalidCredentials': 'Correo o contraseña inválidos. Por favor intente de nuevo.',
      'errNetwork': 'Error de red. Comprueba tu conexión e intenta de nuevo.',
      'errAccountCreation': 'Error al crear la cuenta. Es posible que ya exista una cuenta con este correo.',
      'passwordResetSent': 'Instrucciones de restablecimiento enviadas a tu correo.',
      'healthProfileTitle': 'Conozcámonos un poco mejor.',
      'signOut': 'Cerrar Sesión',
      'switchTheme': 'Cambiar Tema',
      'systemTheme': 'Sistema',
      'lightTheme': 'Claro',
      'darkTheme': 'Oscuro',
      'aiCoach': 'Entrenador IA',
      'workouts': 'Entrenamientos',
      'nutrition': 'Nutrición',
      'progress': 'Progreso',
      'healthAssessment': 'Evaluación de Salud',
      'visionAssessment': 'Evaluación de Visión',

      'step1Title': 'Información Básica',
      'step1Subtitle': 'Cuéntanos sobre ti para calcular tu base biométrica.',
      'metricUnits': 'Métrico (cm / kg)',
      'imperialUnits': 'Imperial (ft / lbs)',
      'age': 'Edad',
      'sex': 'Sexo',
      'male': 'Masculino',
      'female': 'Femenino',
      'otherSex': 'No binario / Otro',
      'heightCm': 'Altura (cm)',
      'weightKg': 'Peso (kg)',
      'heightFt': 'Pies',
      'heightIn': 'Pulgadas',
      'weightLbs': 'Peso (lbs)',

      'step2Title': '¿Qué tan activo eres?',
      'step2Subtitle': 'Selecciona el nivel que mejor describa tu rutina.',
      'sedentary': 'Sedentario',
      'sedentaryDesc': 'Poco o ningún ejercicio, trabajo de escritorio',
      'lightlyActive': 'Ligeramente Activo',
      'lightlyActiveDesc': 'Ejercicio ligero 1-3 días/semana',
      'moderatelyActive': 'Moderadamente Activo',
      'moderatelyActiveDesc': 'Ejercicio moderado 3-5 días/semana',
      'veryActive': 'Muy Activo',
      'veryActiveDesc': 'Ejercicio fuerte 6-7 días/semana',
      'extremelyActive': 'Extremadamente Activo',
      'extremelyActiveDesc': 'Ejercicio muy intenso y trabajo físico',

      'step3Title': '¿Cuál es tu objetivo principal?',
      'step3Subtitle': 'Selecciona tu objetivo prioritario.',
      'loseWeight': 'Perder peso',
      'buildMuscle': 'Ganar músculo',
      'improveFitness': 'Mejorar condición física',
      'improveEndurance': 'Mejorar resistencia',
      'maintainWeight': 'Mantener peso',
      'improveHealth': 'Mejorar salud general',

      'step4Title': 'Estilo de Vida',
      'step4Subtitle': 'Ayúdanos a adaptar un plan a tu horario.',
      'workoutTimePerDay': 'Tiempo de entrenamiento por día',
      'workoutDaysPerWeek': 'Días preferidos por semana',
      'equipmentAvailable': 'Equipamiento disponible',
      'sleepDuration': 'Duración del sueño',
      'dietaryPreference': 'Preferencia dietética',

      'step5Title': 'Resumen Biométrico y IMC',
      'step5Subtitle': 'Base de salud calculada localmente.',
      'bmiValue': 'Índice IMC',
      'bmiDisclaimerTitle': 'Aviso de Métrica de Cribado',
      'bmiDisclaimerText': 'El Índice de Masa Corporal (IMC) es una métrica general de evaluación. No mide directamente la grasa corporal y no es un diagnóstico médico.',
      'underweight': 'Bajo peso',
      'normalWeight': 'Peso normal',
      'overweight': 'Sobrepeso',
      'obesity': 'Obesidad',
      'finishAssessment': 'Completar Perfil',
      'homeDashboardTitle': 'Bienvenido a FitnessElite',
      'homeDashboardSubtitle': 'Tu perfil de fitness está activo.',
    },
    'zh': {
      'appName': 'FitnessElite.ai',
      'welcomeTitle': '精英AI健身',
      'welcomeSubtitle': '健身数字孪生！您的身体。模拟。优化。',
      'taglineCaps': '您的身体。模拟。优化。',
      'fitnessInYourLanguage': '用您的语言健身。',
      'choosePreferredLanguage': '选择您的首选语言。您可以随时更改。',
      'searchLanguage': '搜索语言...',
      'getStarted': '立即开始',
      'skip': '跳过',
      'next': '下一步',
      'continueButton': '继续',
      'onboardingHeadline1': '了解您的身体。',
      'onboardingSubtitle1': 'FitnessElite.ai 了解您的目标、生活方式和健身需求。',
      'onboardingHeadline2': '您的计划。由AI驱动。',
      'onboardingSubtitle2': '获得量身定制的训练、营养指导和进度洞察。',
      'onboardingHeadline3': '成为更强大的自己。',
      'onboardingSubtitle3': '追踪您的进度，建立持久的习惯。',
      'journeyStartsHere': '您的旅程由此开始。',
      'authTitle': '身份验证基础',
      'authSubtitle': '安全访问您的生物识别性能中心',
      'revisitOnboarding': '重新查看引导',
      'changeLanguage': '更改语言',
      'welcomeToFitnessElite': '欢迎使用 FitnessElite.ai',
      'authSubtitleTagline': '您的个性化健身之旅由此开始。',
      'signIn': '登录',
      'createAccount': '创建账户',
      'fullName': '全名',
      'fullNameHint': '请输入您的全名',
      'emailAddress': '电子邮件',
      'emailHint': 'name@example.com',
      'password': '密码',
      'confirmPassword': '确认密码',
      'forgotPassword': '忘记密码？',
      'orDivider': '或',
      'continueWithGoogle': '使用 Google 继续',
      'alreadyHaveAccount': '已有账户？登录',
      'dontHaveAccount': '还没有账户？创建账户',
      'validationNameRequired': '请输入全名',
      'validationEmailInvalid': '请输入有效的电子邮件地址',
      'validationPasswordMin': '密码必须至少为8个字符',
      'validationPasswordMatch': '密码不匹配',
      'errInvalidCredentials': '电子邮件或密码无效。请重试。',
      'errNetwork': '网络错误。请检查您的连接并重试。',
      'errAccountCreation': '创建账户失败。使用此电子邮件的账户可能已存在。',
      'passwordResetSent': '密码重置说明已发送至您的电子邮箱。',
      'healthProfileTitle': '让我们了解一下您。',
      'signOut': '退出登录',
      'switchTheme': '切换主题',
      'systemTheme': '跟随系统',
      'lightTheme': '浅色',
      'darkTheme': '深色',
      'aiCoach': 'AI教练',
      'workouts': '训练课程',
      'nutrition': '营养管理',
      'progress': '进度追踪',
      'healthAssessment': '健康评估',
      'visionAssessment': '视觉评估',

      'step1Title': '基本信息',
      'step1Subtitle': '告诉我们关于您的信息以计算生物识别基线。',
      'metricUnits': '公制 (厘米 / 公斤)',
      'imperialUnits': '英制 (英尺 / 磅)',
      'age': '年龄',
      'sex': '性别',
      'male': '男',
      'female': '女',
      'otherSex': '非二元/其他',
      'heightCm': '身高 (厘米)',
      'weightKg': '体重 (公斤)',
      'heightFt': '英尺',
      'heightIn': '英寸',
      'weightLbs': '体重 (磅)',

      'step2Title': '您的活动量如何？',
      'step2Subtitle': '选择最符合您日常生活的级别。',
      'sedentary': '久坐不动',
      'sedentaryDesc': '几乎不运动，办公室工作',
      'lightlyActive': '轻度活动',
      'lightlyActiveDesc': '每周轻度运动 1-3 天',
      'moderatelyActive': '中度活动',
      'moderatelyActiveDesc': '每周中度运动 3-5 天',
      'veryActive': '高度活动',
      'veryActiveDesc': '每周剧烈运动 6-7 天',
      'extremelyActive': '极高活动',
      'extremelyActiveDesc': '高强度运动与体力劳动',

      'step3Title': '您的主要健身目标是什么？',
      'step3Subtitle': '选择您的首要目标。',
      'loseWeight': '减轻体重',
      'buildMuscle': '增加肌肉',
      'improveFitness': '提升体能',
      'improveEndurance': '提高耐力',
      'maintainWeight': '保持体重',
      'improveHealth': '改善整体健康',

      'step4Title': '生活方式与偏好',
      'step4Subtitle': '帮助我们根据您的日程安排制定计划。',
      'workoutTimePerDay': '每天锻炼时间',
      'workoutDaysPerWeek': '每周偏好天数',
      'equipmentAvailable': '可用器材',
      'sleepDuration': '睡眠时长',
      'dietaryPreference': '饮食偏好',

      'step5Title': '生物识别摘要与BMI',
      'step5Subtitle': '本地计算的健康基线。',
      'bmiValue': 'BMI 指数',
      'bmiDisclaimerTitle': '筛查指标声明',
      'bmiDisclaimerText': '身体质量指数 (BMI) 是基于身高和体重的通用筛查指标。它不直接测量体脂，也不是医学诊断。',
      'underweight': '体重过轻',
      'normalWeight': '体重正常',
      'overweight': '超重',
      'obesity': '肥胖',
      'finishAssessment': '完成档案',
      'homeDashboardTitle': '欢迎来到 FitnessElite',
      'homeDashboardSubtitle': '您的健身档案已建立。',
    },
    'hi': {
      'appName': 'FitnessElite.ai',
      'welcomeTitle': 'फ़िटनेस एलीट AI',
      'welcomeSubtitle': 'फ़िटनेस डिजिटल ट्विन! आपका शरीर। सिम्युलेटेड। ऑप्टिमाइज्ड।',
      'taglineCaps': 'आपका शरीर। सिम्युलेटेड। ऑप्टिमाइज्ड।',
      'fitnessInYourLanguage': 'फ़िटनेस, आपकी भाषा में।',
      'choosePreferredLanguage': 'अपनी पसंदीदा भाषा चुनें। आप इसे कभी भी बदल सकते हैं।',
      'searchLanguage': 'भाषा खोजें...',
      'getStarted': 'शुरू करें',
      'skip': 'छोड़ें',
      'next': 'आगे बढ़ें',
      'continueButton': 'जारी रखें',
      'onboardingHeadline1': 'अपने शरीर को समझें।',
      'onboardingSubtitle1': 'FitnessElite.ai आपके लक्ष्यों, जीवनशैली और फिटनेस आवश्यकताओं को सीखता है।',
      'onboardingHeadline2': 'आपकी योजना। AI द्वारा संचालित।',
      'onboardingSubtitle2': 'व्यक्तिगत वर्कआउट, पोषण मार्गदर्शन और प्रगति की जानकारी प्राप्त करें।',
      'onboardingHeadline3': 'एक मजबूत संस्करण बनें।',
      'onboardingSubtitle3': 'अपनी प्रगति पर नज़र रखें और ऐसी आदतें बनाएँ जो बनी रहें।',
      'journeyStartsHere': 'आपकी यात्रा यहाँ से शुरू होती है।',
      'authTitle': 'प्रमाणीकरण फ़ाउंडेशन',
      'authSubtitle': 'आपके बायोमेट्रिक प्रदर्शन हब तक सुरक्षित पहुँच',
      'revisitOnboarding': 'ऑनबोर्डिंग फिर से देखें',
      'changeLanguage': 'भाषा बदलें',
      'welcomeToFitnessElite': 'FitnessElite.ai में आपका स्वागत है',
      'authSubtitleTagline': 'आपकी व्यक्तिगत फिटनेस यात्रा यहाँ से शुरू होती है।',
      'signIn': 'साइन इन करें',
      'createAccount': 'खाता बनाएं',
      'fullName': 'पूरा नाम',
      'fullNameHint': 'अपना पूरा नाम दर्ज करें',
      'emailAddress': 'ईमेल पता',
      'emailHint': 'name@example.com',
      'password': 'पासवर्ड',
      'confirmPassword': 'पासवर्ड की पुष्टि करें',
      'forgotPassword': 'पासवर्ड भूल गए?',
      'orDivider': 'या',
      'continueWithGoogle': 'Google के साथ जारी रखें',
      'alreadyHaveAccount': 'क्या आपके पास पहले से खाता है? साइन इन करें',
      'dontHaveAccount': 'खाता नहीं है? खाता बनाएं',
      'validationNameRequired': 'पूरा नाम आवश्यक है',
      'validationEmailInvalid': 'कृपया एक मान्य ईमेल पता दर्ज करें',
      'validationPasswordMin': 'पासवर्ड कम से कम 8 वर्णों का होना चाहिए',
      'validationPasswordMatch': 'पासवर्ड मेल नहीं खाते',
      'errInvalidCredentials': 'अमान्य ईमेल या पासवर्ड। कृपया पुनः प्रयास करें।',
      'errNetwork': 'नेटवर्क त्रुटि। अपना कनेक्शन जांचें और पुनः प्रयास करें।',
      'errAccountCreation': 'खाता बनाने में विफल। इस ईमेल वाला खाता पहले से मौजूद हो सकता है।',
      'passwordResetSent': 'पासवर्ड रीसेट निर्देश आपके ईमेल पर भेजे गए।',
      'healthProfileTitle': 'आइए आपको बेहतर जानें।',
      'signOut': 'साइन आउट',
      'switchTheme': 'थीम बदलें',
      'systemTheme': 'सिस्टम',
      'lightTheme': 'लाइट',
      'darkTheme': 'डार्क',
      'aiCoach': 'AI कोच',
      'workouts': 'वर्कआउट',
      'nutrition': 'पोषण',
      'progress': 'प्रगति',
      'healthAssessment': 'स्वास्थ्य मूल्यांकन',
      'visionAssessment': 'विज़न मूल्यांकन',

      'step1Title': 'बुनियादी जानकारी',
      'step1Subtitle': 'बायोमेट्रिक बेसलाइन की गणना करने के लिए अपने बारे में बताएं।',
      'metricUnits': 'मैट्रिक (सेमी / किग्रा)',
      'imperialUnits': 'इम्पिरियल (फीट / पाउंड)',
      'age': 'आयु',
      'sex': 'लिंग',
      'male': 'पुरुष',
      'female': 'महिला',
      'otherSex': 'अन्य',
      'heightCm': 'ऊंचाई (सेमी)',
      'weightKg': 'वजन (किग्रा)',
      'heightFt': 'फीट',
      'heightIn': 'इंच',
      'weightLbs': 'वजन (पाउंड)',

      'step2Title': 'आप कितने सक्रिय हैं?',
      'step2Subtitle': 'अपनी दिनचर्या का वर्णन करने वाला स्तर चुनें।',
      'sedentary': 'निष्क्रिय',
      'sedentaryDesc': 'कम या कोई व्यायाम नहीं',
      'lightlyActive': 'हल्का सक्रिय',
      'lightlyActiveDesc': 'सप्ताह में 1-3 दिन हल्का व्यायाम',
      'moderatelyActive': 'मध्यम सक्रिय',
      'moderatelyActiveDesc': 'सप्ताह में 3-5 दिन व्यायाम',
      'veryActive': 'बहुत सक्रिय',
      'veryActiveDesc': 'सप्ताह में 6-7 दिन कठिन व्यायाम',
      'extremelyActive': 'अत्यधिक सक्रिय',
      'extremelyActiveDesc': 'अत्यधिक व्यायाम और शारीरिक कार्य',

      'step3Title': 'आपका मुख्य फ़िटनेस लक्ष्य क्या है?',
      'step3Subtitle': 'अपना मुख्य लक्ष्य चुनें।',
      'loseWeight': 'वजन घटाएं',
      'buildMuscle': 'मांसपेशियां बनाएं',
      'improveFitness': 'फिटनेस में सुधार करें',
      'improveEndurance': 'स्टैमिना बढ़ाएं',
      'maintainWeight': 'वजन बनाए रखें',
      'improveHealth': 'समग्र स्वास्थ्य में सुधार करें',

      'step4Title': 'जीवनशैली और प्राथमिकताएं',
      'step4Subtitle': 'अपने शेड्यूल के अनुसार योजना बनाने में मदद करें।',
      'workoutTimePerDay': 'प्रतिदिन वर्कआउट का समय',
      'workoutDaysPerWeek': 'प्रति सप्ताह पसंदीदा दिन',
      'equipmentAvailable': 'उपलब्ध उपकरण',
      'sleepDuration': 'नींद की अवधि',
      'dietaryPreference': 'आहार प्राथमिकता',

      'step5Title': 'बायोमेट्रिक सारांश और बीएमआई',
      'step5Subtitle': 'स्थानीय रूप से गणना की गई स्वास्थ्य बेसलाइन।',
      'bmiValue': 'बीएमआई स्कोर',
      'bmiDisclaimerTitle': 'स्क्रीनिंग मीट्रिक अस्वीकरण',
      'bmiDisclaimerText': 'बॉडी मास इंडेक्स (BMI) एक सामान्य स्क्रीनिंग मीट्रिक है। यह सीधे शरीर की चर्बी नहीं मापता है और यह कोई चिकित्सीय निदान नहीं है।',
      'underweight': 'कम वजन',
      'normalWeight': 'सामान्य वजन',
      'overweight': 'अधिक वजन',
      'obesity': 'मोटापा',
      'finishAssessment': 'प्रोफ़ाइल पूरी करें',
      'homeDashboardTitle': 'FitnessElite में आपका स्वागत है',
      'homeDashboardSubtitle': 'आपकी फिटनेस प्रोफाइल सक्रिय है।',
    },
    'ar': {
      'appName': 'FitnessElite.ai',
      'welcomeTitle': 'لياقة نخبويّة بالذكاء الاصطناعي',
      'welcomeSubtitle': 'التوأم الرقمي لللياقة! جسدك. مُحاكى. مُحسّن.',
      'taglineCaps': 'جسدك. مُحاكى. مُحسّن.',
      'fitnessInYourLanguage': 'اللياقة البدنية، بلغتك.',
      'choosePreferredLanguage': 'اختر لغتك المفضلة. يمكنك تغييرها في أي وقت.',
      'searchLanguage': 'البحث عن لغة...',
      'getStarted': 'ابدأ الآن',
      'skip': 'تخطي',
      'next': 'التالي',
      'continueButton': 'متابعة',
      'onboardingHeadline1': 'افهم جسدك.',
      'onboardingSubtitle1': 'يتعرف FitnessElite.ai على أهدافك ونمط حياتك واحتياجات لياقتك البدنية.',
      'onboardingHeadline2': 'خطتك. مدعومة بالذكاء الاصطناعي.',
      'onboardingSubtitle2': 'احصل على تمارين مخصصة وإرشادات تغذية ورؤى حول تقدمك.',
      'onboardingHeadline3': 'كن النسخة الأقوى من نفسك.',
      'onboardingSubtitle3': 'تتبع تقدمك وابنِ عادات تدوم.',
      'journeyStartsHere': 'رحلتك تبدأ من هنا.',
      'authTitle': 'أساس المصادقة',
      'authSubtitle': 'وصول آمن إلى مركز الأداء الحيوي',
      'revisitOnboarding': 'إعادة مراجعة الإعداد',
      'changeLanguage': 'تغيير اللغة',
      'welcomeToFitnessElite': 'مرحباً بك في FitnessElite.ai',
      'authSubtitleTagline': 'رحلتك الرياضية المخصصة تبدأ من هنا.',
      'signIn': 'تسجيل الدخول',
      'createAccount': 'إنشاء حساب',
      'fullName': 'الاسم الكامل',
      'fullNameHint': 'أدخل اسمك الكامل',
      'emailAddress': 'البريد الإلكتروني',
      'emailHint': 'name@example.com',
      'password': 'كلمة المرور',
      'confirmPassword': 'تأكيد كلمة المرور',
      'forgotPassword': 'هل نسيت كلمة المرور؟',
      'orDivider': 'أو',
      'continueWithGoogle': 'المتابعة باستخدام Google',
      'alreadyHaveAccount': 'هل لديك حساب بالفعل؟ تسجيل الدخول',
      'dontHaveAccount': 'ليس لديك حساب؟ إنشاء حساب',
      'validationNameRequired': 'الاسم الكامل مطلوب',
      'validationEmailInvalid': 'يرجى إدخال عنوان بريد إلكتروني صالحة',
      'validationPasswordMin': 'يجب أن تتكون كلمة المرور من 8 أحرف على الأقل',
      'validationPasswordMatch': 'كلمات المرور غير متطابقة',
      'errInvalidCredentials': 'البريد الإلكتروني أو كلمة المرور غير صحيحة. يرجى المحاولة مرة أخرى.',
      'errNetwork': 'خطأ في الشبكة. تحقق من اتصالك وحاول مرة أخرى.',
      'errAccountCreation': 'فشل في إنشاء الحساب. قد يكون هناك حساب بهذا البريد الإلكتروني بالفعل.',
      'passwordResetSent': 'تم إرسال تعليمات إعادة تعيين كلمة المرور إلى بريدك الإلكتروني.',
      'healthProfileTitle': 'دعنا نتعرف عليك.',
      'signOut': 'تسجيل الخروج',
      'switchTheme': 'تغيير المظهر',
      'systemTheme': 'النظام',
      'lightTheme': 'فاتح',
      'darkTheme': 'داكن',
      'aiCoach': 'مدرب الذكاء الاصطناعي',
      'workouts': 'التمارين',
      'nutrition': 'التغذية',
      'progress': 'التقدم',
      'healthAssessment': 'تقييم الصحة',
      'visionAssessment': 'التقييم البصري',

      'step1Title': 'المعلومات الأساسية',
      'step1Subtitle': 'أخبرنا عن نفسك لحساب خط الأساس الحيوي الخاص بك.',
      'metricUnits': 'مترية (سم / كجم)',
      'imperialUnits': 'إمبراطورية (قدم / رطل)',
      'age': 'العمر',
      'sex': 'الجنس',
      'male': 'ذكر',
      'female': 'أنثى',
      'otherSex': 'آخر',
      'heightCm': 'الطول (سم)',
      'weightKg': 'الوزن (كجم)',
      'heightFt': 'قدم',
      'heightIn': 'بوصة',
      'weightLbs': 'الوزن (رطل)',

      'step2Title': 'ما مدى نشاطك؟',
      'step2Subtitle': 'اختر المستوى الذي يصف روتينك اليومي.',
      'sedentary': 'قليل النشاط',
      'sedentaryDesc': 'تمارين قليلة أو معدومة، عمل مكتبي',
      'lightlyActive': 'نشيط خفيف',
      'lightlyActiveDesc': 'تمارين خفيفة 1-3 أيام/الأسبوع',
      'moderatelyActive': 'نشيط معتدل',
      'moderatelyActiveDesc': 'تمارين معتدلة 3-5 أيام/الأسبوع',
      'veryActive': 'نشيط جداً',
      'veryActiveDesc': 'تمارين شاقة 6-7 أيام/الأسبوع',
      'extremelyActive': 'نشيط للغاية',
      'extremelyActiveDesc': 'تمارين شاقة جداً وعمل بدني',

      'step3Title': 'ما هو هدفك الرياضي الرئيسي؟',
      'step3Subtitle': 'اختر هدفك الأساسي.',
      'loseWeight': 'خسارة الوزن',
      'buildMuscle': 'بناء العضلات',
      'improveFitness': 'تحسين اللياقة',
      'improveEndurance': 'تحسين التحمل',
      'maintainWeight': 'الحفاظ على الوزن',
      'improveHealth': 'تحسين الصحة العامة',

      'step4Title': 'نمط الحياة والتفضيلات',
      'step4Subtitle': 'ساعدنا في بناء خطة تتناسب مع جدولك.',
      'workoutTimePerDay': 'وقت التمرين اليومي',
      'workoutDaysPerWeek': 'الأيام المفضلة في الأسبوع',
      'equipmentAvailable': 'المعدات المتاحة',
      'sleepDuration': 'مدة النوم',
      'dietaryPreference': 'التفضيل الغذائي',

      'step5Title': 'الملخص الحيوي ومؤشر كتلة الجسم',
      'step5Subtitle': 'خط أساس صحي محوسب محلياً.',
      'bmiValue': 'مؤشر كتلة الجسم',
      'bmiDisclaimerTitle': 'إخلاء مسؤولية قياس الفحص',
      'bmiDisclaimerText': 'مؤشر كتلة الجسم (BMI) هو مقياس فحص عام قائم على الطول والوزن. لا يقيس الدهون مباشرة ولا يُعد تشخيصاً طبياً.',
      'underweight': 'نقص الوزن',
      'normalWeight': 'وزن طبيعي',
      'overweight': 'زيادة الوزن',
      'obesity': 'السمنة',
      'finishAssessment': 'إكمال الملف',
      'homeDashboardTitle': 'مرحباً بك في FitnessElite',
      'homeDashboardSubtitle': 'ملفك الرياضي نشط الآن.',
    },
    'bn': {
      'appName': 'FitnessElite.ai',
      'welcomeTitle': 'ফিটনেস এলিট এআই',
      'welcomeSubtitle': 'ফিটনেস ডিজিটাল টুইন! আপনার শরীর। সিমুলেটেড। অপ্টিমাইজড।',
      'taglineCaps': 'আপনার শরীর। সিমুলেটেড। অপ্টিমাইজড।',
      'fitnessInYourLanguage': 'ফিটনেস, আপনার ভাষায়।',
      'choosePreferredLanguage': 'আপনার পছন্দের ভাষা বেছে নিন। আপনি এটি যেকোনো সময় পরিবর্তন করতে পারেন।',
      'searchLanguage': 'ভাষা খুঁজুন...',
      'getStarted': 'শুরু করুন',
      'skip': 'এড়িয়ে যান',
      'next': 'পরবর্তী',
      'continueButton': 'চালিয়ে যান',
      'onboardingHeadline1': 'আপনার শরীর বুঝুন।',
      'onboardingSubtitle1': 'FitnessElite.ai আপনার লক্ষ্য, জীবনধারা এবং ফিটনেস চাহিদা বোঝে।',
      'onboardingHeadline2': 'আপনার প্ল্যান। AI চালিত।',
      'onboardingSubtitle2': 'ব্যক্তিগতকৃত ওয়ার্কআউট, পুষ্টির নির্দেশনা এবং অগ্রগতি পর্যবেক্ষণ পান।',
      'onboardingHeadline3': 'হয়ে উঠুন আপনার শক্তিশালী সংস্করণ।',
      'onboardingSubtitle3': 'আপনার অগ্রগতি ট্র্যাক করুন এবং স্থায়ী অভ্যাস গড়ে তুলুন।',
      'journeyStartsHere': 'আপনার যাত্রা এখান থেকেই শুরু।',
      'authTitle': 'অথেন্টিকেশন ফাউন্ডেশন',
      'authSubtitle': 'আপনার বায়োমেট্রিক পারফরম্যান্স হাবে সুরক্ষিত প্রবেশধিকার',
      'revisitOnboarding': 'অনবোর্ডিং পুনরায় দেখুন',
      'changeLanguage': 'ভাষা পরিবর্তন করুন',
      'welcomeToFitnessElite': 'FitnessElite.ai-তে স্বাগতম',
      'authSubtitleTagline': 'আপনার ব্যক্তিগতকৃত ফিটনেস যাত্রা এখান থেকেই শুরু।',
      'signIn': 'সাইন ইন করুন',
      'createAccount': 'অ্যাকাউন্ট তৈরি করুন',
      'fullName': 'পুরো নাম',
      'fullNameHint': 'আপনার পুরো নাম লিখুন',
      'emailAddress': 'ইমেইল ঠিকানা',
      'emailHint': 'name@example.com',
      'password': 'পাসওয়ার্ড',
      'confirmPassword': 'পাসওয়ার্ড নিশ্চিত করুন',
      'forgotPassword': 'পাসওয়ার্ড ভুলে গেছেন?',
      'orDivider': 'অথবা',
      'continueWithGoogle': 'Google দিয়ে চালিয়ে যান',
      'alreadyHaveAccount': 'ইতিমধ্যে একটি অ্যাকাউন্ট আছে? সাইন ইন করুন',
      'dontHaveAccount': 'অ্যাকাউন্ট নেই? অ্যাকাউন্ট তৈরি করুন',
      'validationNameRequired': 'পুরো নাম আবশ্যক',
      'validationEmailInvalid': 'একটি বৈধ ইমেইল ঠিকানা লিখুন',
      'validationPasswordMin': 'পাসওয়ার্ড অন্তত ৮ অক্ষরের হতে হবে',
      'validationPasswordMatch': 'পাসওয়ার্ড দুটি মিলছে না',
      'errInvalidCredentials': 'অবৈধ ইমেইল বা পাসওয়ার্ড। আবার চেষ্টা করুন।',
      'errNetwork': 'নেটওয়ার্ক ত্রুটি। সংযোগ পরীক্ষা করে আবার চেষ্টা করুন।',
      'errAccountCreation': 'অ্যাকাউন্ট তৈরি করা ব্যর্থ হয়েছে। এই ইমেইলে একটি অ্যাকাউন্ট থাকতে পারে।',
      'passwordResetSent': 'পাসওয়ার্ড রিসেট নির্দেশাবলী আপনার ইমেইলে পাঠানো হয়েছে।',
      'healthProfileTitle': 'চলুন আপনাকে আরও চিনে নিই।',
      'signOut': 'সাইন আউট',
      'switchTheme': 'থিম পরিবর্তন করুন',
      'systemTheme': 'সিস্টেম',
      'lightTheme': 'লাইট',
      'darkTheme': 'ডার্ক',
      'aiCoach': 'AI কোচ',
      'workouts': 'ওয়ার্কআউট',
      'nutrition': 'পুষ্টি',
      'progress': 'অগ্রগতি',
      'healthAssessment': 'স্বাস্থ্য মূল্যায়ন',
      'visionAssessment': 'ভিশন মূল্যায়ন',

      'step1Title': 'মৌলিক তথ্য',
      'step1Subtitle': 'বায়োমেট্রিক বেসলাইন গণনা করতে আপনার তথ্য দিন।',
      'metricUnits': 'মেট্রিক (সেমি / কেজি)',
      'imperialUnits': 'ইম্পেরিয়াল (ফুট / পাউন্ড)',
      'age': 'বয়স',
      'sex': 'লিঙ্গ',
      'male': 'পুরুষ',
      'female': 'মহিলা',
      'otherSex': 'অন্যান্য',
      'heightCm': 'উচ্চতা (সেমি)',
      'weightKg': 'ওজন (কেজি)',
      'heightFt': 'ফুট',
      'heightIn': 'ইঞ্চি',
      'weightLbs': 'ওজন (পাউন্ড)',

      'step2Title': 'আপনি কতটা সক্রিয়?',
      'step2Subtitle': 'আপনার রুটিন অনুযায়ী স্তর বেছে নিন।',
      'sedentary': 'এক জায়গায় বসে কাজ',
      'sedentaryDesc': 'খুব কম বা কোনো ব্যায়াম নেই',
      'lightlyActive': 'হালকা সক্রিয়',
      'lightlyActiveDesc': 'সপ্তাহে ১-৩ দিন হালকা ব্যায়াম',
      'moderatelyActive': 'মাঝারি সক্রিয়',
      'moderatelyActiveDesc': 'সপ্তাহে ৩-৫ দিন ব্যায়াম',
      'veryActive': 'খুব সক্রিয়',
      'veryActiveDesc': 'সপ্তাহে ৬-৭ দিন কঠোর ব্যায়াম',
      'extremelyActive': 'অত্যন্ত সক্রিয়',
      'extremelyActiveDesc': 'অত্যধিক ব্যায়াম ও শারীরিক পরিশ্রম',

      'step3Title': 'আপনার প্রধান ফিটনেস লক্ষ্য কী?',
      'step3Subtitle': 'আপনার মূল লক্ষ্য বেছে নিন।',
      'loseWeight': 'ওজন কমানো',
      'buildMuscle': 'পেশি তৈরি',
      'improveFitness': 'ফিটনেস উন্নত করা',
      'improveEndurance': 'স্ট্যামিনা বাড়ানো',
      'maintainWeight': 'ওজন বজায় রাখা',
      'improveHealth': 'সামগ্রিক স্বাস্থ্য উন্নতি',

      'step4Title': 'জীবনধারা ও পছন্দ',
      'step4Subtitle': 'সময়সূচী অনুযায়ী পরিকল্পনা করতে সাহায্য করুন।',
      'workoutTimePerDay': 'দৈনিক ওয়ার্কআউটের সময়',
      'workoutDaysPerWeek': 'সপ্তাহে পছন্দের দিন',
      'equipmentAvailable': 'উপলব্ধ সরঞ্জাম',
      'sleepDuration': 'ঘুমের সময়কাল',
      'dietaryPreference': 'খাদ্য পছন্দ',

      'step5Title': 'বায়োমেট্রিক সারসংক্ষেপ ও বিএমআই',
      'step5Subtitle': 'লোকালি গণনাকৃত স্বাস্থ্য তথ্য।',
      'bmiValue': 'বিএমআই স্কোর',
      'bmiDisclaimerTitle': 'স্ক্রিনিং মেট্রিক ডিসক্লেইমার',
      'bmiDisclaimerText': 'বডি মাস ইনডেক্স (BMI) একটি সাধারণ স্ক্রিনিং মেট্রিক। এটি সরাসরি শরীরের চর্বি পরিমাপ করে না এবং কোনো চিকিৎসা ডায়াগনসিস নয়।',
      'underweight': 'স্বাভাবিকের চেয়ে কম ওজন',
      'normalWeight': 'স্বাভাবিক ওজন',
      'overweight': 'অতিরিক্ত ওজন',
      'obesity': 'স্থূলতা',
      'finishAssessment': 'প্রোফাইল সম্পন্ন করুন',
      'homeDashboardTitle': 'FitnessElite-এ স্বাগতম',
      'homeDashboardSubtitle': 'আপনার ফিটনেস প্রোফাইল সক্রিয় হয়েছে।',
    },
    'te': {
      'appName': 'FitnessElite.ai',
      'welcomeTitle': 'ఫిట్‌నెస్ ఎలైట్ AI',
      'welcomeSubtitle': 'ఫిట్‌నెస్ డిజిటల్ ట్విన్! మీ శరీరం. సిమ్యులేట్ చేయబడింది. ఆప్టిమైజ్ చేయబడింది.',
      'taglineCaps': 'మీ శరీరం. సిమ్యులేట్ చేయబడింది. ఆప్టిమైజ్ చేయబడింది.',
      'fitnessInYourLanguage': 'ఫిట్‌నెస్, మీ భాషలో.',
      'choosePreferredLanguage': 'మీకు కావలసిన భాషను ఎంచుకోండి. మీరు దీన్ని ఎప్పుడైనా మార్చవచ్చు.',
      'searchLanguage': 'భాషను శోధించండి...',
      'getStarted': 'ప్రారంభించండి',
      'skip': 'స్కిప్ చేయండి',
      'next': 'తరువాత',
      'continueButton': 'కొనసాగించండి',
      'onboardingHeadline1': 'మీ శరీరాన్ని అర్థం చేసుకోండి.',
      'onboardingSubtitle1': 'FitnessElite.ai మీ లక్ష్యాలు, జీవనశైలి మరియు ఫిట్‌నెస్ అవసరాలను నేర్చుకుంటుంది.',
      'onboardingHeadline2': 'మీ ప్రణాళిక. AI మద్దతుతో.',
      'onboardingSubtitle2': 'అనుకూలీకరించిన వర్కౌట్స్, పోషకాహార మార్గదర్శకత్వం పొందండి.',
      'onboardingHeadline3': 'మరింత బలంగా మారండి.',
      'onboardingSubtitle3': 'మీ పురోగతిని ట్రాక్ చేయండి మరియు శాశ్వత అలవాట్లను నిర్మించుకోండి.',
      'journeyStartsHere': 'మీ ప్రయాణం ఇక్కడ ప్రారంభమవుతుంది.',
      'authTitle': 'అథెంటికేషన్ ఫౌండేషన్',
      'authSubtitle': 'మీ బయోమెట్రిక్ ప్రదర్శన కేంద్రానికి సురక్షిత ప్రవేశం',
      'revisitOnboarding': 'ఆన్‌బోర్డింగ్ మళ్లీ చూడండి',
      'changeLanguage': 'భాష మార్చండి',
      'welcomeToFitnessElite': 'FitnessElite.aiకి స్వాగతం',
      'authSubtitleTagline': 'మీ వ్యక్తిగత ఫిట్‌నెస్ ప్రయాణం ఇక్కడ ప్రారంభమవుతుంది.',
      'signIn': 'సైన్ ఇన్ చేయండి',
      'createAccount': 'ఖాతాను సృష్టించండి',
      'fullName': 'పూర్తి పేరు',
      'fullNameHint': 'మీ పూర్తి పేరును నమోదు చేయండి',
      'emailAddress': 'ఈమెయిల్ చిరునామా',
      'emailHint': 'name@example.com',
      'password': 'పాస్‌వర్డ్',
      'confirmPassword': 'పాస్‌వర్డ్‌ను ధృవీకరించండి',
      'forgotPassword': 'పాస్‌వర్డ్ మర్చిపోయారా?',
      'orDivider': 'లేదా',
      'continueWithGoogle': 'Googleతో కొనసాగండి',
      'alreadyHaveAccount': 'ఇప్పటికే ఖాతా ఉందా? సైన్ ఇన్ చేయండి',
      'dontHaveAccount': 'ఖాతా లేదా? ఖాతాను సృష్టించండి',
      'validationNameRequired': 'పూర్తి పేరు అవసరం',
      'validationEmailInvalid': 'దయచేసి చెల్లుబాటు అయ్యే ఈమెయిల్ చిరునామాను నమోదు చేయండి',
      'validationPasswordMin': 'పాస్‌వర్డ్ కనీసం 8 అక్షరాలు ఉండాలి',
      'validationPasswordMatch': 'పాస్‌వర్డ్‌లు సరిపోలడం లేదు',
      'errInvalidCredentials': 'చెల్లని ఈమెయిల్ లేదా పాస్‌వర్డ్. దయచేసి మళ్లీ ప్రయత్నించండి.',
      'errNetwork': 'నెట్‌వర్క్ లోపం. మీ కనెక్షన్‌ని తనిఖీ చేసి మళ్లీ ప్రయత్నించండి.',
      'errAccountCreation': 'ఖాతాను సృష్టించడం విఫలమైంది. ఈ ఈమెయిల్‌తో ఖాతా ముందే ఉండి ఉండవచ్చు.',
      'passwordResetSent': 'మీ ఈమెయిల్‌కు పాస్‌వర్డ్ రీసెట్ సూచనలు పంపబడ్డాయి.',
      'healthProfileTitle': 'మిమ్మల్ని పరిచయం చేసుకుందాం.',
      'signOut': 'సైన్ అవుట్',
      'switchTheme': 'థీమ్ మార్చండి',
      'systemTheme': 'సిస్టమ్',
      'lightTheme': 'లైట్',
      'darkTheme': 'డార్క్',
      'aiCoach': 'AI కోచ్',
      'workouts': 'వర్కవుట్స్',
      'nutrition': 'పోషణ',
      'progress': 'పురోగతి',
      'healthAssessment': 'ఆరోగ్య అంచనా',
      'visionAssessment': 'విజన్ అంచనా',

      'step1Title': 'ప్రాథమిక సమాచారం',
      'step1Subtitle': 'మీ బయోమెట్రిక్ బేస్‌లైన్‌ను లెక్కించడానికి మీ వివరాలను నమోదు చేయండి.',
      'metricUnits': 'మెట్రిక్ (సెం.మీ / కేజీ)',
      'imperialUnits': 'ఇంపీరియల్ (ఫీట్లు / పౌండ్లు)',
      'age': 'వయస్సు',
      'sex': 'లింగం',
      'male': 'పురుషుడు',
      'female': 'స్త్రీ',
      'otherSex': 'ఇతర',
      'heightCm': 'ఎత్తు (సెం.మీ)',
      'weightKg': 'బరువు (కేజీ)',
      'heightFt': 'ఫీట్లు',
      'heightIn': 'అంగుళాలు',
      'weightLbs': 'బరువు (పౌండ్లు)',

      'step2Title': 'మీరు ఎంత చురుకుగా ఉన్నారు?',
      'step2Subtitle': 'మీ దినచర్యను ఉత్తమంగా వివరించే స్థాయిని ఎంచుకోండి.',
      'sedentary': 'కూర్చుని చేసే పని',
      'sedentaryDesc': 'తక్కువ లేదా వ్యాయామం లేదు',
      'lightlyActive': 'కొద్దిగా చురుకైన',
      'lightlyActiveDesc': 'వారానికి 1-3 రోజులు తేలికపాటి వ్యాయామం',
      'moderatelyActive': 'సాధారణంగా చురుకైన',
      'moderatelyActiveDesc': 'వారానికి 3-5 రోజులు వ్యాయామం',
      'veryActive': 'చాలా చురుకైన',
      'veryActiveDesc': 'వారానికి 6-7 రోజులు కష్టమైన వ్యాయామం',
      'extremelyActive': 'అత్యంత చురుకైన',
      'extremelyActiveDesc': 'తీవ్రమైన వ్యాయామం & శారీరక శ్రమ',

      'step3Title': 'మీ ప్రధాన ఫిట్‌నెస్ లక్ష్యం ఏమిటి?',
      'step3Subtitle': 'మీ ప్రాథమిక లక్ష్యాన్ని ఎంచుకోండి.',
      'loseWeight': 'బరువు తగ్గడం',
      'buildMuscle': 'కండరాలను నిర్మించడం',
      'improveFitness': 'ఫిట్‌నెస్‌ను మెరుగుపరచడం',
      'improveEndurance': 'స్టామిటాను పెంచడం',
      'maintainWeight': 'బరువును నిర్వహించడం',
      'improveHealth': 'ఆరోగ్యాన్ని మెరుగుపరచడం',

      'step4Title': 'జీవనశైలి & ప్రాధాన్యతలు',
      'step4Subtitle': 'మీ సమయానికి తగినట్లు ప్రణాళికను సిద్ధం చేయండి.',
      'workoutTimePerDay': 'రోజువారీ వ్యాయామ సమయం',
      'workoutDaysPerWeek': 'వారానికి ఇష్టమైన రోజులు',
      'equipmentAvailable': 'అందుబాటులో ఉన్న పరికరాలు',
      'sleepDuration': 'నిద్ర సమయం',
      'dietaryPreference': 'ఆహార ప్రాధాన్యత',

      'step5Title': 'బయోమెట్రిక్ సారాంశం & BMI',
      'step5Subtitle': 'స్థానికంగా లెక్కించబడిన ఆరోగ్య బేస్‌లైన్.',
      'bmiValue': 'బిఎమ్‌ఐ స్కోరు',
      'bmiDisclaimerTitle': 'స్కిన్నింగ్ మెట్రిక్ నిరాకరణ',
      'bmiDisclaimerText': 'బాడీ మాస్ ఇండెక్స్ (BMI) అనేది ఎత్తు మరియు బరువుపై ఆధారపడిన సాధారణ స్క్రీనింగ్ కొలత. ఇది శరీర కొవ్వును నేరుగా కొలవదు మరియు ఇది వైద్య నిర్ధారణ కాదు.',
      'underweight': 'తక్కువ బరువు',
      'normalWeight': 'సాధారణ బరువు',
      'overweight': 'అధిక బరువు',
      'obesity': 'బొద్దుతనం / స్థూలకాయం',
      'finishAssessment': 'ప్రొఫైల్‌ను పూర్తి చేయండి',
      'homeDashboardTitle': 'FitnessEliteకి స్వాగతం',
      'homeDashboardSubtitle': 'మీ ఫిట్‌నెస్ ప్రొఫైల్ సక్రియంగా ఉంది.',
    },
    'mr': {
      'appName': 'FitnessElite.ai',
      'welcomeTitle': 'फिटनेस एलिट AI',
      'welcomeSubtitle': 'फिटनेस डिजिटल ट्विन! तुमचे शरीर. सिम्युलेटेड. ऑप्टिमाइझ केलेले.',
      'taglineCaps': 'तुमचे शरीर. सिम्युलेटेड. ऑप्टिमाइझ केलेले.',
      'fitnessInYourLanguage': 'फिटनेस, तुमच्या भाषेत.',
      'choosePreferredLanguage': 'तुमची आवडती भाषा निवडा. तुम्ही हे कधीही बदलू शकता.',
      'searchLanguage': 'भाषा शोधा...',
      'getStarted': 'सुरू करा',
      'skip': 'वगळा',
      'next': 'पुढील',
      'continueButton': 'पुढे जा',
      'onboardingHeadline1': 'तुमचे शरीर समजून घ्या.',
      'onboardingSubtitle1': 'FitnessElite.ai तुमची ध्येये, जीवनशैली आणि फिटनेस गरजा जाणून घेते.',
      'onboardingHeadline2': 'तुमची योजना. AI द्वारे संचलित.',
      'onboardingSubtitle2': 'वैयक्तिकृत वर्कआउट्स, पोषण मार्गदर्शन आणि प्रगतीची माहिती मिळवा.',
      'onboardingHeadline3': 'अधिक मजबूत बना.',
      'onboardingSubtitle3': 'तुमच्या प्रगतीचा मागोवा घ्या आणि टिकणाऱ्या सवयी लावा.',
      'journeyStartsHere': 'तुमचा प्रवास येथून सुरू होतो.',
      'authTitle': 'प्रमाणीकरण पाया',
      'authSubtitle': 'तुमच्या बायोमेट्रिक परफॉर्मन्स हबमध्ये सुरक्षित प्रवेश',
      'revisitOnboarding': 'ऑनबोर्डिंग पुन्हा पहा',
      'changeLanguage': 'भाषा बदला',
      'welcomeToFitnessElite': 'FitnessElite.ai मध्ये आपले स्वागत आहे',
      'authSubtitleTagline': 'तुमचा वैयक्तिकृत फिटनेस प्रवास येथून सुरू होतो.',
      'signIn': 'साइन इन करा',
      'createAccount': 'खाते तयार करा',
      'fullName': 'पूर्ण नाव',
      'fullNameHint': 'तुमचे पूर्ण नाव प्रविष्ट करा',
      'emailAddress': 'ईमेल पत्ता',
      'emailHint': 'name@example.com',
      'password': 'पासवर्ड',
      'confirmPassword': 'पासवर्डची खात्री करा',
      'forgotPassword': 'पासवर्ड विसरलात?',
      'orDivider': 'किंवा',
      'continueWithGoogle': 'Google सह सुरू ठेवा',
      'alreadyHaveAccount': 'आधीच खाते आहे? साइन इन करा',
      'dontHaveAccount': 'खाते नाही? खाते तयार करा',
      'validationNameRequired': 'पूर्ण नाव आवश्यक आहे',
      'validationEmailInvalid': 'कृपया एक वैध ईमेल पत्ता प्रविष्ट करा',
      'validationPasswordMin': 'पासवर्ड किमान 8 अक्षरांचा असावा',
      'validationPasswordMatch': 'पासवर्ड जुळत नाहीत',
      'errInvalidCredentials': 'अवैध ईमेल किंवा पासवर्ड. कृपया पुन्हा प्रयत्न करा.',
      'errNetwork': 'नेटवर्क त्रुटी. तुमचे कनेक्शन तपासा आणि पुन्हा प्रयत्न करा.',
      'errAccountCreation': 'खाते तयार करण्यात अयशस्वी. या ईमेलसह खाते आधीच अस्तित्वात असू शकते.',
      'passwordResetSent': 'पासवर्ड रीसेट सूचना तुमच्या ईमेलवर पाठवल्या आहेत.',
      'healthProfileTitle': 'चला तुमची ओळख करून घेऊया.',
      'signOut': 'साइन आउट',
      'switchTheme': 'थीम बदला',
      'systemTheme': 'सिस्टम',
      'lightTheme': 'लाइट',
      'darkTheme': 'डार्क',
      'aiCoach': 'AI कोच',
      'workouts': 'वर्कआउट्स',
      'nutrition': 'पोषण',
      'progress': 'प्रगती',
      'healthAssessment': 'आरोग्य मूल्यमापन',
      'visionAssessment': 'व्हिजन मूल्यमापन',

      'step1Title': 'मूलभूत माहिती',
      'step1Subtitle': 'बायोमेट्रिक बेसलाइनची गणना करण्यासाठी माहिती द्या.',
      'metricUnits': 'मॅट्रिक (सेमी / किग्रॅ)',
      'imperialUnits': 'इम्पिरियल (फूट / पाउंड)',
      'age': 'वय',
      'sex': 'लिंग',
      'male': 'पुरुष',
      'female': 'स्त्री',
      'otherSex': 'इतर',
      'heightCm': 'उंची (सेमी)',
      'weightKg': 'वजन (किग्रॅ)',
      'heightFt': 'फूट',
      'heightIn': 'इंच',
      'weightLbs': 'वजन (पाउंड)',

      'step2Title': 'तुम्ही किती सक्रिय आहात?',
      'step2Subtitle': 'तुमच्या दिनचर्येचे वर्णन करणारी पातळी निवडा.',
      'sedentary': 'निष्क्रिय',
      'sedentaryDesc': 'कमी किंवा व्यायाम नाही',
      'lightlyActive': 'हळूवार सक्रिय',
      'lightlyActiveDesc': 'आठवड्यातून १-३ दिवस व्यायाम',
      'moderatelyActive': 'मध्यम सक्रिय',
      'moderatelyActiveDesc': 'आठवड्यातून ३-५ दिवस व्यायाम',
      'veryActive': 'खूप सक्रिय',
      'veryActiveDesc': 'आठवड्यातून ६-७ दिवस कठीण व्यायाम',
      'extremelyActive': 'अत्यंत सक्रिय',
      'extremelyActiveDesc': 'अत्यंत कठीण व्यायाम आणि शारीरिक काम',

      'step3Title': 'तुमचे मुख्य फिटनेस ध्येय काय आहे?',
      'step3Subtitle': 'तुमचे मुख्य ध्येय निवडा.',
      'loseWeight': 'वजन कमी करणे',
      'buildMuscle': 'स्नायू तयार करणे',
      'improveFitness': 'फिटनेस सुधारणे',
      'improveEndurance': 'स्टॅमिना वाढवणे',
      'maintainWeight': 'वजन राखणे',
      'improveHealth': 'आरोग्य सुधारणे',

      'step4Title': 'जीवनशैली आणि प्राधान्ये',
      'step4Subtitle': 'तुमच्या वेळेनुसार योजना तयार करण्यात मदत करा.',
      'workoutTimePerDay': 'दररोज वर्कआउट वेळ',
      'workoutDaysPerWeek': 'दर आठवड्याला आवडते दिवस',
      'equipmentAvailable': 'उपलब्ध साधने',
      'sleepDuration': 'झोपेचा कालावधी',
      'dietaryPreference': 'आहार प्राधान्य',

      'step5Title': 'बायोमेट्रिक सारांश आणि बीएमआय',
      'step5Subtitle': 'स्थानिक पातळीवर मोजलेली आरोग्य बेसलाइन.',
      'bmiValue': 'बीएमआय स्कोअर',
      'bmiDisclaimerTitle': 'स्क्रीनिंग मेट्रिक अस्वीकरण',
      'bmiDisclaimerText': 'बॉडी मास इंडेक्स (BMI) हे सामान्य स्क्रीनिंग मेट्रिक आहे. हे थेट चरबी मोजत नाही आणि हे वैद्यकीय निदान नाही.',
      'underweight': 'कमी वजन',
      'normalWeight': 'सामान्य वजन',
      'overweight': 'जास्त वजन',
      'obesity': 'स्थूलता',
      'finishAssessment': 'प्रोफाइल पूर्ण करा',
      'homeDashboardTitle': 'FitnessElite मध्ये स्वागत आहे',
      'homeDashboardSubtitle': 'तुमचे फिटनेस प्रोफाइल सक्रिय आहे.',
    },
    'ta': {
      'appName': 'FitnessElite.ai',
      'welcomeTitle': 'ஃபிட்னஸ் எலைட் AI',
      'welcomeSubtitle': 'ஃபிட்னஸ் டிஜிட்டல் ட்வின்! உங்கள் உடல். உருவகப்படுத்தப்பட்டது. மேம்படுத்தப்பட்டது.',
      'taglineCaps': 'உங்கள் உடல். உருவகப்படுத்தப்பட்டது. மேம்படுத்தப்பட்டது.',
      'fitnessInYourLanguage': 'ஃபிட்னஸ், உங்கள் மொழியில்.',
      'choosePreferredLanguage': 'మీకు விருப்பமான மொழியைத் தேர்ந்தெடுக்கவும். எப்போது வேண்டுமானாலும் மாற்றலாம்.',
      'searchLanguage': 'மொழியைத் தேடுங்கள்...',
      'getStarted': 'தொடங்கவும்',
      'skip': 'தவிர்க்கவும்',
      'next': 'அடுத்து',
      'continueButton': 'தொடரவும்',
      'onboardingHeadline1': 'உங்கள் உடலைப் புரிந்து கொள்ளுங்கள்.',
      'onboardingSubtitle1': 'FitnessElite.ai உங்கள் இலக்குகள், வாழ்க்கை முறை மற்றும் ஃபிட்னஸ் தேவைகளைக் கற்றுக்கொள்கிறது.',
      'onboardingHeadline2': 'உங்கள் திட்டம். AI மூலம் இயங்குகிறது.',
      'onboardingSubtitle2': 'தனிப்பயனாக்கப்பட்ட பயிற்சிகள், ஊட்டச்சத்து வழிகாட்டுதல் மற்றும் முன்னேற்ற நுண்ணறிவுகளைப் பெறுங்கள்.',
      'onboardingHeadline3': 'உங்களின் வலிமையான பதிப்பாக மாறுங்கள்.',
      'onboardingSubtitle3': 'உங்கள் முன்னேற்றத்தைக் கண்காணித்து, நீடிக்கும் பழக்கங்களை உருவாக்குங்கள்.',
      'journeyStartsHere': 'உங்கள் பயணம் இங்கே தொடங்குகிறது.',
      'authTitle': 'அடைப்புமுறை அடித்தளம்',
      'authSubtitle': 'உங்கள் பயோமெட்ரிக் செயல்திறன் மையத்திற்கு பாதுகாப்பான அணுகல்',
      'revisitOnboarding': 'ஆன்போர்டிங்கை மீண்டும் பார்க்கவும்',
      'changeLanguage': 'மொழியை மாற்றவும்',
      'welcomeToFitnessElite': 'FitnessElite.ai-க்கு வரவேற்கிறோம்',
      'authSubtitleTagline': 'உங்கள் தனிப்பயனாக்கப்பட்ட ஃபிட்னஸ் பயணம் இங்கே தொடங்குகிறது.',
      'signIn': 'லாகின் செய்யவும்',
      'createAccount': 'கணக்கை உருவாக்கவும்',
      'fullName': 'முழு பெயர்',
      'fullNameHint': 'உங்கள் முழு பெயரை உள்ளிடவும்',
      'emailAddress': 'மின்னஞ்சல் முகவரி',
      'emailHint': 'name@example.com',
      'password': 'கடவுச்சொல்',
      'confirmPassword': 'கடவுச்சொல்லை உறுதிப்படுத்தவும்',
      'forgotPassword': 'கடவுச்சொல்லை மறந்துவிட்டீர்களா?',
      'orDivider': 'அல்லது',
      'continueWithGoogle': 'Google மூலம் தொடரவும்',
      'alreadyHaveAccount': 'ஏற்கனவே கணக்கு உள்ளதா? லாகின் செய்யவும்',
      'dontHaveAccount': 'கணக்கு இல்லையா? கணக்கை உருவாக்கவும்',
      'validationNameRequired': 'முழு பெயர் தேவை',
      'validationEmailInvalid': 'செல்லுபடியாகும் மின்னஞ்சல் முகவரியை உள்ளிடவும்',
      'validationPasswordMin': 'கடவுச்சொல் കുറഞ്ഞது 8 எழுத்துக்களாக இருக்க வேண்டும்',
      'validationPasswordMatch': 'கடவுச்சொற்கள் பொருந்தவில்லை',
      'errInvalidCredentials': 'தவறான மின்னஞ்சல் அல்லது கடவுச்சொல். மீண்டும் முயற்சிக்கவும்.',
      'errNetwork': 'நெட்வொர்க் பிழை. இணைப்பைச் சரிபார்த்து மீண்டும் முயற்சிக்கவும்.',
      'errAccountCreation': 'கணக்கை உருவாக்குவது தோல்வியடைந்தது. இந்த மின்னஞ்சலில் ஏற்கனவே கணக்கு இருக்கலாம்.',
      'passwordResetSent': 'கடவுச்சொல் மீட்டமைப்பு சூചനகள் உங்கள் மின்னஞ்சலுக்கு அனுப்பப்பட்டன.',
      'healthProfileTitle': 'உங்களைப் பற்றி தெரிந்து கொள்வோம்.',
      'signOut': 'சைன் அவுட்',
      'switchTheme': 'தீம் மாற்றவும்',
      'systemTheme': 'சிஸ்டம்',
      'lightTheme': 'லைட்',
      'darkTheme': 'டார்க்',
      'aiCoach': 'AI பயிற்சியாளர்',
      'workouts': 'பயிற்சிகள்',
      'nutrition': 'ஊட்டச்சத்து',
      'progress': 'முன்னேற்றம்',
      'healthAssessment': 'ஆரோக்கிய மதிப்பீடு',
      'visionAssessment': 'பார்வை மதிப்பீடு',

      'step1Title': 'அடிப்படை விவரங்கள்',
      'step1Subtitle': 'பயோமெட்ரிக் கணக்கீட்டிற்கு உங்களைப் பற்றிய தகவல்களை வழங்கவும்.',
      'metricUnits': 'மெட்ரிக் (செ.மீ / கி.கி)',
      'imperialUnits': 'இம்பீரியல் (அடி / பவுண்ட்)',
      'age': 'வயது',
      'sex': 'பாலினம்',
      'male': 'ஆண்',
      'female': 'பெண்',
      'otherSex': 'மற்றவை',
      'heightCm': 'உயரம் (செ.மீ)',
      'weightKg': 'எடை (கி.கி)',
      'heightFt': 'அடி',
      'heightIn': 'அங்குலம்',
      'weightLbs': 'எடை (பவுண்ட்)',

      'step2Title': 'நீங்கள் எவ்வளவு சுறுசுறுப்பாக இருக்கிறீர்கள்?',
      'step2Subtitle': 'உங்கள் வழக்கத்திற்கு ஏற்ற நிலையைத் தேர்ந்தெடுக்கவும்.',
      'sedentary': 'குறைந்த சுறுசுறுப்பு',
      'sedentaryDesc': 'குறைந்த பயிற்சி அல்லது மேஜை வேலை',
      'lightlyActive': 'மிதமான சுறுசுறுப்பு',
      'lightlyActiveDesc': 'வாரத்திற்கு 1-3 நாட்கள் பயிற்சி',
      'moderatelyActive': 'நடுத்தர சுறுசுறுப்பு',
      'moderatelyActiveDesc': 'வாரத்திற்கு 3-5 நாட்கள் பயிற்சி',
      'veryActive': 'அதிக சுறுசுறுப்பு',
      'veryActiveDesc': 'வாரத்திற்கு 6-7 நாட்கள் பயிற்சி',
      'extremelyActive': 'மிகவும் சுறுசுறுப்பு',
      'extremelyActiveDesc': 'கடுமையான பயிற்சி & உடலுழைப்பு',

      'step3Title': 'உங்கள் முக்கிய ஃபிட்னஸ் இலக்கு என்ன?',
      'step3Subtitle': 'உங்கள் முதன்மை இலக்கைத் தேர்ந்தெடுக்கவும்.',
      'loseWeight': 'எடை குறைத்தல்',
      'buildMuscle': 'தசையை உருவாக்குதல்',
      'improveFitness': 'ஃபிட்னஸை மேம்படுத்துதல்',
      'improveEndurance': 'தாங்குதிறனை அதிகரித்தல்',
      'maintainWeight': 'எடையைப் பராமரித்தல்',
      'improveHealth': 'ஆரோக்கியத்தை மேம்படுத்துதல்',

      'step4Title': 'வாழ்க்கை முறை & விருப்பங்கள்',
      'step4Subtitle': 'உங்கள் நேரத்திற்கு ஏற்ப திட்டமிட உதவுங்கள்.',
      'workoutTimePerDay': 'தினசரி பயிற்சி நேரம்',
      'workoutDaysPerWeek': 'வாரத்தில் விரும்பும் நாட்கள்',
      'equipmentAvailable': 'உள்ள உபகரணங்கள்',
      'sleepDuration': 'தூக்க நேரம்',
      'dietaryPreference': 'உணவு விருப்பம்',

      'step5Title': 'பயோமெட்ரிக் சுருக்கம் & BMI',
      'step5Subtitle': 'உள்ளூர் கணக்கீட்டு ஆரோக்கிய அடிப்படை.',
      'bmiValue': 'BMI மதிப்பீடு',
      'bmiDisclaimerTitle': 'திரையிடல் அளவீட்டு மறுப்பு',
      'bmiDisclaimerText': 'உடல் நிறை குறியீடு (BMI) என்பது உயரம் மற்றும் எடையை அடிப்படையாகக் கொண்ட பொதுவான திரையிடல் அளவீடு ஆகும். இது நேரடியாக உடல் கொழுப்பை அளவிடாது மற்றும் மருத்துவ நோயறிதல் அல்ல.',
      'underweight': 'குறைந்த எடை',
      'normalWeight': 'இயல்பான எடை',
      'overweight': 'அதிக எடை',
      'obesity': 'உடல் பருமன்',
      'finishAssessment': 'சுயவிவரத்தை முடிக்கவும்',
      'homeDashboardTitle': 'FitnessElite-க்கு வரவேற்கிறோம்',
      'homeDashboardSubtitle': 'உங்கள் ஃபிட்னஸ் சுயவிவரம் செயலில் உள்ளது.',
    },
  };

  String translate(String key) {
    final languageCode = locale.languageCode;
    return _localizedValues[languageCode]?[key] ??
        _localizedValues['en']?[key] ??
        key;
  }

  // Helper getters
  String get appName => translate('appName');
  String get welcomeTitle => translate('welcomeTitle');
  String get welcomeSubtitle => translate('welcomeSubtitle');
  String get taglineCaps => translate('taglineCaps');
  String get fitnessInYourLanguage => translate('fitnessInYourLanguage');
  String get choosePreferredLanguage => translate('choosePreferredLanguage');
  String get searchLanguage => translate('searchLanguage');
  String get getStarted => translate('getStarted');
  String get skip => translate('skip');
  String get next => translate('next');
  String get continueButton => translate('continueButton');
  String get onboardingHeadline1 => translate('onboardingHeadline1');
  String get onboardingSubtitle1 => translate('onboardingSubtitle1');
  String get onboardingTitle => translate('onboardingHeadline1');
  String get onboardingSubtitle => translate('onboardingSubtitle1');
  String get onboardingHeadline2 => translate('onboardingHeadline2');
  String get onboardingSubtitle2 => translate('onboardingSubtitle2');
  String get onboardingHeadline3 => translate('onboardingHeadline3');
  String get onboardingSubtitle3 => translate('onboardingSubtitle3');
  String get journeyStartsHere => translate('journeyStartsHere');
  String get authTitle => translate('authTitle');
  String get authSubtitle => translate('authSubtitle');
  String get revisitOnboarding => translate('revisitOnboarding');
  String get changeLanguage => translate('changeLanguage');

  // Auth Getters
  String get welcomeToFitnessElite => translate('welcomeToFitnessElite');
  String get authSubtitleTagline => translate('authSubtitleTagline');
  String get signIn => translate('signIn');
  String get createAccount => translate('createAccount');
  String get fullName => translate('fullName');
  String get fullNameHint => translate('fullNameHint');
  String get emailAddress => translate('emailAddress');
  String get emailHint => translate('emailHint');
  String get password => translate('password');
  String get confirmPassword => translate('confirmPassword');
  String get forgotPassword => translate('forgotPassword');
  String get orDivider => translate('orDivider');
  String get continueWithGoogle => translate('continueWithGoogle');
  String get alreadyHaveAccount => translate('alreadyHaveAccount');
  String get dontHaveAccount => translate('dontHaveAccount');
  String get validationNameRequired => translate('validationNameRequired');
  String get validationEmailInvalid => translate('validationEmailInvalid');
  String get validationPasswordMin => translate('validationPasswordMin');
  String get validationPasswordMatch => translate('validationPasswordMatch');
  String get errInvalidCredentials => translate('errInvalidCredentials');
  String get errNetwork => translate('errNetwork');
  String get errAccountCreation => translate('errAccountCreation');
  String get passwordResetSent => translate('passwordResetSent');
  String get healthProfileTitle => translate('healthProfileTitle');
  String get signOut => translate('signOut');

  // Health Assessment Getters
  String get step1Title => translate('step1Title');
  String get step1Subtitle => translate('step1Subtitle');
  String get metricUnits => translate('metricUnits');
  String get imperialUnits => translate('imperialUnits');
  String get age => translate('age');
  String get sex => translate('sex');
  String get male => translate('male');
  String get female => translate('female');
  String get otherSex => translate('otherSex');
  String get heightCm => translate('heightCm');
  String get weightKg => translate('weightKg');
  String get heightFt => translate('heightFt');
  String get heightIn => translate('heightIn');
  String get weightLbs => translate('weightLbs');

  String get step2Title => translate('step2Title');
  String get step2Subtitle => translate('step2Subtitle');
  String get sedentary => translate('sedentary');
  String get sedentaryDesc => translate('sedentaryDesc');
  String get lightlyActive => translate('lightlyActive');
  String get lightlyActiveDesc => translate('lightlyActiveDesc');
  String get moderatelyActive => translate('moderatelyActive');
  String get moderatelyActiveDesc => translate('moderatelyActiveDesc');
  String get veryActive => translate('veryActive');
  String get veryActiveDesc => translate('veryActiveDesc');
  String get extremelyActive => translate('extremelyActive');
  String get extremelyActiveDesc => translate('extremelyActiveDesc');

  String get step3Title => translate('step3Title');
  String get step3Subtitle => translate('step3Subtitle');
  String get loseWeight => translate('loseWeight');
  String get buildMuscle => translate('buildMuscle');
  String get improveFitness => translate('improveFitness');
  String get improveEndurance => translate('improveEndurance');
  String get maintainWeight => translate('maintainWeight');
  String get improveHealth => translate('improveHealth');

  String get step4Title => translate('step4Title');
  String get step4Subtitle => translate('step4Subtitle');
  String get workoutTimePerDay => translate('workoutTimePerDay');
  String get workoutDaysPerWeek => translate('workoutDaysPerWeek');
  String get equipmentAvailable => translate('equipmentAvailable');
  String get sleepDuration => translate('sleepDuration');
  String get dietaryPreference => translate('dietaryPreference');

  String get step5Title => translate('step5Title');
  String get step5Subtitle => translate('step5Subtitle');
  String get bmiValue => translate('bmiValue');
  String get bmiDisclaimerTitle => translate('bmiDisclaimerTitle');
  String get bmiDisclaimerText => translate('bmiDisclaimerText');
  String get underweight => translate('underweight');
  String get normalWeight => translate('normalWeight');
  String get overweight => translate('overweight');
  String get obesity => translate('obesity');
  String get finishAssessment => translate('finishAssessment');
  String get homeDashboardTitle => translate('homeDashboardTitle');
  String get homeDashboardSubtitle => translate('homeDashboardSubtitle');

  String get switchTheme => translate('switchTheme');
  String get systemTheme => translate('systemTheme');
  String get lightTheme => translate('lightTheme');
  String get darkTheme => translate('darkTheme');
  String get aiCoach => translate('aiCoach');
  String get workouts => translate('workouts');
  String get nutrition => translate('nutrition');
  String get progress => translate('progress');
  String get healthAssessment => translate('healthAssessment');
  String get visionAssessment => translate('visionAssessment');

  bool get isRtl => locale.languageCode == 'ar';
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return AppLocalizations.supportedLocales
        .any((supported) => supported.languageCode == locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
