import 'dart:convert';
import 'fitness_goal.dart';
import 'nutrition_plan.dart';
import 'recovery_plan.dart';
import 'workout_day.dart';
import 'workout_plan.dart';

/// Aggregated, complete personalized Fitness Plan generated by FitnessEngineService.
class FitnessPlan {
  final String id;
  final DateTime createdAt;
  final int durationWeeks;
  final String summary;
  final String primaryGoal;
  final List<FitnessGoal> targetMetrics;
  final List<WorkoutDay> weeklySchedule;
  final WorkoutPlan workoutPlan;
  final NutritionPlan nutritionPlan;
  final RecoveryPlan recoveryPlan;

  const FitnessPlan({
    required this.id,
    required this.createdAt,
    required this.durationWeeks,
    required this.summary,
    required this.primaryGoal,
    required this.targetMetrics,
    required this.weeklySchedule,
    required this.workoutPlan,
    required this.nutritionPlan,
    required this.recoveryPlan,
  });

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'createdAt': createdAt.toIso8601String(),
      'durationWeeks': durationWeeks,
      'summary': summary,
      'primaryGoal': primaryGoal,
      'targetMetrics': targetMetrics.map((e) => e.toMap()).toList(),
      'weeklySchedule': weeklySchedule.map((e) => e.toMap()).toList(),
      'workoutPlan': workoutPlan.toMap(),
      'nutritionPlan': nutritionPlan.toMap(),
      'recoveryPlan': recoveryPlan.toMap(),
    };
  }

  factory FitnessPlan.fromMap(Map<String, dynamic> map) {
    return FitnessPlan(
      id: map['id'] as String? ?? 'plan_default',
      createdAt: map['createdAt'] != null
          ? DateTime.parse(map['createdAt'] as String)
          : DateTime.now(),
      durationWeeks: (map['durationWeeks'] as num?)?.toInt() ?? 4,
      summary: map['summary'] as String? ?? '',
      primaryGoal: map['primaryGoal'] as String? ?? 'Improve overall fitness',
      targetMetrics: (map['targetMetrics'] as List<dynamic>?)
              ?.map((e) => FitnessGoal.fromMap(e as Map<String, dynamic>))
              .toList() ??
          [],
      weeklySchedule: (map['weeklySchedule'] as List<dynamic>?)
              ?.map((e) => WorkoutDay.fromMap(e as Map<String, dynamic>))
              .toList() ??
          [],
      workoutPlan: map['workoutPlan'] != null
          ? WorkoutPlan.fromMap(map['workoutPlan'] as Map<String, dynamic>)
          : const WorkoutPlan(title: '', description: '', weeklyFrequency: 3),
      nutritionPlan: map['nutritionPlan'] != null
          ? NutritionPlan.fromMap(map['nutritionPlan'] as Map<String, dynamic>)
          : const NutritionPlan(
              dailyCalories: 2000,
              proteinGrams: 120,
              carbsGrams: 220,
              fatGrams: 65,
              hydrationLiters: 2.5,
              dietaryPreference: 'Flexible',
              guidanceNotes: '',
            ),
      recoveryPlan: map['recoveryPlan'] != null
          ? RecoveryPlan.fromMap(map['recoveryPlan'] as Map<String, dynamic>)
          : const RecoveryPlan(
              sleepTargetHours: '7-8 hours',
              restDaysPerWeek: 2,
              hydrationGuidance: '2.5 L',
              mobilityRecommendation: 'Stretching',
              recoveryNotes: '',
            ),
    );
  }

  String toJson() => json.encode(toMap());

  factory FitnessPlan.fromJson(String source) =>
      FitnessPlan.fromMap(json.decode(source) as Map<String, dynamic>);
}
