import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import '../../../../app/theme/app_colors.dart';
import '../../../../core/constants/app_constants.dart';
import '../../../../core/utils/responsive_utils.dart';
import '../../../../shared/animations/fade_in_animation.dart';
import '../../../../shared/animations/glass_entrance_animation.dart';
import '../../../../shared/animations/slide_in_animation.dart';
import '../../../../shared/widgets/fitness_elite_logo.dart';
import '../../../../shared/widgets/glass_card.dart';
import '../../../ai_coach/providers/ai_coach_provider.dart';
import '../../providers/fitness_engine_provider.dart';
import '../widgets/goals_preview_card.dart';
import '../widgets/nutrition_preview_card.dart';
import '../widgets/recovery_preview_card.dart';
import '../widgets/workout_preview_card.dart';

/// Personalized Fitness Plan Screen generated by FitnessEngine.
class PersonalizedPlanScreen extends ConsumerWidget {
  const PersonalizedPlanScreen({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final isDark = Theme.of(context).brightness == Brightness.dark;
    final horizontalPadding = ResponsiveUtils.getHorizontalPadding(context);
    final engineState = ref.watch(fitnessEngineNotifierProvider);
    final aiState = ref.watch(conversationNotifierProvider);

    final plan = engineState.currentPlan;

    if (plan == null) {
      return Scaffold(
        appBar: AppBar(
          centerTitle: true,
          title: const FitnessEliteLogo(iconSize: 26, fontSize: 18),
        ),
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              const Text('No plan generated yet.'),
              const SizedBox(height: 12),
              ElevatedButton(
                onPressed: () => context.go('/plan-generation'),
                child: const Text('Generate Fitness Plan'),
              ),
            ],
          ),
        ),
      );
    }

    final hp = aiState.completeProfile?.healthProfile;
    final pref = aiState.completeProfile?.fitnessPreferences;

    return Scaffold(
      appBar: AppBar(
        centerTitle: true,
        title: const FitnessEliteLogo(
          iconSize: 26,
          fontSize: 18,
        ),
        leading: IconButton(
          icon: const Icon(Icons.arrow_back_rounded),
          onPressed: () => context.go('/ai-coach'),
        ),
      ),
      body: SafeArea(
        child: Padding(
          padding: EdgeInsets.symmetric(horizontal: horizontalPadding),
          child: Column(
            children: [
              Expanded(
                child: SingleChildScrollView(
                  padding: const EdgeInsets.symmetric(vertical: 16),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.stretch,
                    children: [
                      // Badge
                      SlideInAnimation(
                        direction: SlideDirection.down,
                        child: Align(
                          alignment: Alignment.centerLeft,
                          child: Container(
                            padding: const EdgeInsets.symmetric(
                                horizontal: 12, vertical: 6),
                            decoration: BoxDecoration(
                              color: AppColors.electricBlue
                                  .withValues(alpha: 0.18),
                              borderRadius: BorderRadius.circular(20),
                              border:
                                  Border.all(color: AppColors.electricBlue),
                            ),
                            child: Row(
                              mainAxisSize: MainAxisSize.min,
                              children: const [
                                Icon(Icons.auto_awesome_rounded,
                                    size: 14, color: AppColors.electricBlue),
                                SizedBox(width: 6),
                                Text(
                                  'PERSONALIZED FOR YOU',
                                  style: TextStyle(
                                    color: AppColors.electricBlue,
                                    fontSize: 12,
                                    fontWeight: FontWeight.w800,
                                    letterSpacing: 0.8,
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ),
                      ),

                      const SizedBox(height: 12),

                      // Header Title
                      SlideInAnimation(
                        direction: SlideDirection.up,
                        child: Text(
                          'Your Fitness Plan',
                          style: Theme.of(context).textTheme.displaySmall?.copyWith(
                                fontWeight: FontWeight.w800,
                              ),
                        ),
                      ),

                      const SizedBox(height: 6),

                      // Summary
                      FadeInAnimation(
                        delay: const Duration(milliseconds: 150),
                        child: Text(
                          plan.summary,
                          style: Theme.of(context).textTheme.bodyLarge?.copyWith(
                                color: isDark
                                    ? AppColors.darkTextSecondary
                                    : AppColors.lightTextSecondary,
                              ),
                        ),
                      ),

                      const SizedBox(height: 20),

                      // Quick Specs Grid
                      GlassEntranceAnimation(
                        delay: const Duration(milliseconds: 200),
                        child: GlassCard(
                          padding: const EdgeInsets.all(16),
                          child: Row(
                            mainAxisAlignment: MainAxisAlignment.spaceAround,
                            children: [
                              _SpecItem(
                                icon: Icons.flag_rounded,
                                label: 'GOAL',
                                value: plan.primaryGoal,
                              ),
                              _SpecItem(
                                icon: Icons.calendar_month_rounded,
                                label: 'FREQUENCY',
                                value: '${plan.workoutPlan.weeklyFrequency} days/wk',
                              ),
                              _SpecItem(
                                icon: Icons.timer_rounded,
                                label: 'DURATION',
                                value: hp?.workoutAvailability ?? pref?.dailyTrainingTime ?? "30 min",
                              ),
                              _SpecItem(
                                icon: Icons.location_on_rounded,
                                label: 'LOCATION',
                                value: pref?.preferredLocation ?? 'Home',
                              ),
                            ],
                          ),
                        ),
                      ),

                      const SizedBox(height: 20),

                      // Section 1: WORKOUT
                      WorkoutPreviewCard(
                        plan: plan.workoutPlan,
                        delayMs: 250,
                      ),

                      const SizedBox(height: 16),

                      // Section 2: NUTRITION
                      NutritionPreviewCard(
                        plan: plan.nutritionPlan,
                        delayMs: 350,
                      ),

                      const SizedBox(height: 16),

                      // Section 3: RECOVERY
                      RecoveryPreviewCard(
                        plan: plan.recoveryPlan,
                        delayMs: 450,
                      ),

                      const SizedBox(height: 16),

                      // Section 4: GOALS
                      GoalsPreviewCard(
                        goals: plan.targetMetrics,
                        delayMs: 550,
                      ),

                      const SizedBox(height: 16),
                    ],
                  ),
                ),
              ),

              // Bottom Start My Plan Button
              Padding(
                padding: const EdgeInsets.only(bottom: AppConstants.defaultPadding),
                child: GlassEntranceAnimation(
                  delay: const Duration(milliseconds: 650),
                  child: SizedBox(
                    width: double.infinity,
                    height: 56,
                    child: ElevatedButton.icon(
                      onPressed: () => context.go('/home'),
                      icon: const Icon(Icons.rocket_launch_rounded, size: 20),
                      label: const Text('Start My Plan'),
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class _SpecItem extends StatelessWidget {
  final IconData icon;
  final String label;
  final String value;

  const _SpecItem({
    required this.icon,
    required this.label,
    required this.value,
  });

  @override
  Widget build(BuildContext context) {
    return Expanded(
      child: Column(
        children: [
          Icon(icon, size: 18, color: AppColors.electricBlue),
          const SizedBox(height: 4),
          Text(
            label,
            style: const TextStyle(
              fontSize: 9,
              fontWeight: FontWeight.w800,
              color: AppColors.electricBlue,
            ),
          ),
          const SizedBox(height: 2),
          Text(
            value,
            textAlign: TextAlign.center,
            maxLines: 2,
            overflow: TextOverflow.ellipsis,
            style: Theme.of(context).textTheme.bodySmall?.copyWith(
                  fontWeight: FontWeight.w800,
                  fontSize: 11,
                ),
          ),
        ],
      ),
    );
  }
}
